/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E08_Checks;

import java.util.Enumeration;
import javax.swing.JCheckBox;

/**
 *
 * @author DAM2Alu3
 */
public class JFrameChecks extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameChecks.class.getName());

    /**
     * Creates new form JFrameChecks
     */
    String modulos[] = {"SGE", "DI", "AD", "Ingles", "PDM", "PSP", "Empresa"};
    JCheckBox[] jcb = new JCheckBox[modulos.length];
    
    private void compruebaTodos(){
       // jCheckBox1TodosActionPerformed(evt);
       jCheckBox1Todos.setSelected(true);
       for(JCheckBox jc : jcb ){
           if(!jc.isSelected()){
               jCheckBox1Todos.setSelected(false);
               break;
           }
       }
    }
    
    private void cargaChecks(){
        int pos = 0;
        for(String modulo : modulos){
            jcb[pos] = new JCheckBox(modulo);
            jcb[pos].addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compruebaTodos();
            }
            });
            jPanelChecks.add(jcb[pos]);
            pos++;
        }
    }
    public JFrameChecks() {
        initComponents();
        cargaChecks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelChecks = new javax.swing.JPanel();
        jCheckBox1Todos = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTION MATRICULA");

        jPanelChecks.setBackground(new java.awt.Color(153, 255, 255));
        jPanelChecks.setLayout(new javax.swing.BoxLayout(jPanelChecks, javax.swing.BoxLayout.PAGE_AXIS));

        jCheckBox1Todos.setText("Todos");
        jCheckBox1Todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1TodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelChecks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCheckBox1Todos)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jCheckBox1Todos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelChecks, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1TodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1TodosActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1Todos.isSelected()) {
            for(JCheckBox jc : jcb){
                jc.setSelected(true);
            }
        }
        
        /*  int pos = 0;

            for(String modulo : modulos){
                jcb[pos].setSelected(true);
                pos++;
            }        
        */
    }//GEN-LAST:event_jCheckBox1TodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameChecks().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1Todos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelChecks;
    // End of variables declaration//GEN-END:variables
}
