/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E03_Layout;

import javax.swing.JButton;

/**
 *
 * @author DAM2Alu3
 */
public class JFrame6CardLayout extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame6CardLayout.class.getName());

    /**
     * Creates new form JFrame6CardLayout
     */
    public JFrame6CardLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCliente = new javax.swing.JButton();
        jButtonVehiculos = new javax.swing.JButton();
        jPanelPadre = new javax.swing.JPanel();
        jPanelVehiculo = new javax.swing.JPanel();
        jLabelVehiculos = new javax.swing.JLabel();
        jPanelClientes = new javax.swing.JPanel();
        jLabelClientes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCliente.setText("Clientes");
        jButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizaPanel(evt);
            }
        });
        jPanel1.add(jButtonCliente);

        jButtonVehiculos.setText("Vehículos");
        jButtonVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizaPanel(evt);
            }
        });
        jPanel1.add(jButtonVehiculos);

        jPanelPadre.setLayout(new java.awt.CardLayout());

        jLabelVehiculos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelVehiculos.setForeground(new java.awt.Color(153, 0, 153));
        jLabelVehiculos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVehiculos.setText("VEHICULOS");
        jLabelVehiculos.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanelVehiculoLayout = new javax.swing.GroupLayout(jPanelVehiculo);
        jPanelVehiculo.setLayout(jPanelVehiculoLayout);
        jPanelVehiculoLayout.setHorizontalGroup(
            jPanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
        jPanelVehiculoLayout.setVerticalGroup(
            jPanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
        );

        jPanelPadre.add(jPanelVehiculo, "card4");

        jLabelClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelClientes.setForeground(new java.awt.Color(153, 0, 153));
        jLabelClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClientes.setText("CLIENTES");
        jLabelClientes.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanelClientesLayout = new javax.swing.GroupLayout(jPanelClientes);
        jPanelClientes.setLayout(jPanelClientesLayout);
        jPanelClientesLayout.setHorizontalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
        jPanelClientesLayout.setVerticalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanelPadre.add(jPanelClientes, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizaPanel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizaPanel
        // TODO add your handling code here:
        JButton jbutton = (JButton)evt.getSource();
         jPanelPadre.removeAll();
        if (jbutton == jButtonCliente) {
            jPanelPadre.add(jPanelClientes);
                        
        } else if(jbutton == jButtonVehiculos){
            jPanelPadre.add(jPanelVehiculo);
        }
        
        jPanelPadre.repaint();
        jPanelPadre.revalidate();
    }//GEN-LAST:event_ActualizaPanel

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrame6CardLayout().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonVehiculos;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelVehiculos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JPanel jPanelPadre;
    private javax.swing.JPanel jPanelVehiculo;
    // End of variables declaration//GEN-END:variables
}
