/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package E14_Table;

import java.util.Date;

/**
 *
 * @author DAM2Alu3
 */
public class JDialogEditCliente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogEditCliente.class.getName());

    /**
     * Creates new form JDialogAltaCliente
     */
    
    JFrameTable jframepadre;
    
    public void cargaID(){
        jComboBoxId.removeAllItems();
        for(Cliente cliente : LogicaNegocio.getClientes()){
            jComboBoxId.addItem(String.valueOf(cliente.getId()));
        }
    }
    
    public JDialogEditCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        jframepadre = (JFrameTable)parent;
        initComponents();
        cargaID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JLabelId = new javax.swing.JLabel();
        jComboBoxId = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelProvincia = new javax.swing.JLabel();
        jComboBoxProvoncia = new javax.swing.JComboBox<>();
        jLabelMail = new javax.swing.JLabel();
        jTextFieldMail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelFechaAlta = new javax.swing.JLabel();
        jSpinnerFechaAlta = new javax.swing.JSpinner();
        jButtonAlta = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ALTA CLIENTES");

        jPanel1.setLayout(new java.awt.GridLayout(7, 2, 10, 10));

        JLabelId.setText("ID");
        jPanel1.add(JLabelId);

        jComboBoxId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxIdItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxId);

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNombre);

        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3);
        jPanel1.add(jTextFieldApellido);

        jLabelProvincia.setText("Provincia");
        jPanel1.add(jLabelProvincia);

        jComboBoxProvoncia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Huesca", "Zaragoza", "Teruel" }));
        jPanel1.add(jComboBoxProvoncia);

        jLabelMail.setText("Mail");
        jPanel1.add(jLabelMail);

        jTextFieldMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMailActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldMail);

        jLabel4.setText("Edad");
        jPanel1.add(jLabel4);

        jTextFieldEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdadActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEdad);

        jLabelFechaAlta.setText("Fecha Alta");
        jPanel1.add(jLabelFechaAlta);

        jSpinnerFechaAlta.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFechaAlta.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFechaAlta, "dd/MM/yyyy hh:mm"));
        jPanel1.add(jSpinnerFechaAlta);

        jButtonAlta.setText("Alta");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAlta)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlta)
                    .addComponent(jButtonCancelar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMailActionPerformed

    private void jTextFieldEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdadActionPerformed

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        // TODO add your handling code here:
       /* Cliente nuevo = new Cliente(
                        jTextFieldNombre.getText(),
                        jTextFieldApellido.getText(),
                        jComboBoxProvoncia.getSelectedItem().toString(),
                        jTextFieldMail.getText(),
                        Integer.parseInt(jTextFieldEdad.getText()),
                        (Date)jSpinnerFechaAlta.getValue());
        
        jframepadre.addCliente(nuevo);*/
       int id = Integer.parseInt(jComboBoxId.getSelectedItem().toString());
       Cliente cliente = LogicaNegocio.getCliente(id);
       cliente.setNombre(jTextFieldNombre.getText());
       cliente.setApellidos(jTextFieldApellido.getText());
       cliente.setProvincia(jComboBoxProvoncia.getSelectedItem().toString());
       cliente.setMail(jTextFieldMail.getText());
       cliente.setEdad(Integer.parseInt(jTextFieldEdad.getText()));
       cliente.setFecha((Date)jSpinnerFechaAlta.getValue());
       LogicaNegocio.editCliente(cliente);
       
       jframepadre.CargaInicial();
       dispose();
    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void jComboBoxIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxIdItemStateChanged
        // TODO add your handling code here:
        if(jComboBoxId.getSelectedItem()!= null){
            int id = Integer.parseInt(jComboBoxId.getSelectedItem().toString());
            Cliente cliente = LogicaNegocio.getCliente(id);
            jTextFieldNombre.setText(cliente.getNombre());
            jTextFieldApellido.setText(cliente.getApellidos());
            jComboBoxProvoncia.setSelectedItem(cliente.getProvincia());
            jTextFieldMail.setText(cliente.getMail());
            jTextFieldEdad.setText(String.valueOf(cliente.getEdad()));
            jSpinnerFechaAlta.setValue(cliente.getFecha());
            
            
        }
    }//GEN-LAST:event_jComboBoxIdItemStateChanged

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogEditCliente dialog = new JDialogEditCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelId;
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox<String> jComboBoxId;
    private javax.swing.JComboBox<String> jComboBoxProvoncia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFechaAlta;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelProvincia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerFechaAlta;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
