/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.ConexionBBDD;
import Controlador.EmpleadoDAO;
import Controlador.Seguridad;
import Modelo.Empleado;
import com.formdev.flatlaf.intellijthemes.FlatCobalt2IJTheme;
import java.util.Date;

/**
 *
 * @author DAM2Alu4
 * 
 */
public class JDialogCrearEmpleado extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogCrearEmpleado.class.getName());

    EmpleadoDAO c = new EmpleadoDAO();
    // carga Paises
    private void cargarPaises() {
        String[] paises = {"España","Francia","Italia","Alemania","Portugal","Reino Unido",
            "Estados Unidos","Canadá","México","Argentina","Brasil","Colombia","Perú","Chile",
            "Venezuela","China","Japón","Corea del Sur","India","Marruecos","Argelia","Egipto",
            "Rusia","Ucrania","Polonia","Rumanía","Países Bajos","Suecia","Noruega","Australia","Otro"};
        jComboBoxPais.removeAllItems();
        for (String p : paises) jComboBoxPais.addItem(p);
        jComboBoxPais.setSelectedItem("España");
    }
    public JDialogCrearEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarPaises();
        setTitle("Crear empleados");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelid = new javax.swing.JLabel();
        jTextDNI_NIE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jLabelApellido2 = new javax.swing.JLabel();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jLabelFechaAlta = new javax.swing.JLabel();
        jSpinnerFechaAlt = new javax.swing.JSpinner();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelContraseña1 = new javax.swing.JLabel();
        jTContraseña1 = new javax.swing.JTextField();
        jLabelContraseña2 = new javax.swing.JLabel();
        jTContraseña2 = new javax.swing.JTextField();
        jLabelRol = new javax.swing.JLabel();
        jComboBoxROL = new javax.swing.JComboBox<>();
        jLabelCorreo = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelNacionalidad = new javax.swing.JLabel();
        jComboBoxNacionalidad = new javax.swing.JComboBox<>();
        jLabelPais = new javax.swing.JLabel();
        jComboBoxPais = new javax.swing.JComboBox<>();
        jLabelCalle_numero = new javax.swing.JLabel();
        jTextFieldCalle_Numero = new javax.swing.JTextField();
        jLabelPoblacion = new javax.swing.JLabel();
        jTextFieldPoblacion = new javax.swing.JTextField();
        jLabelPiso = new javax.swing.JLabel();
        jTextFieldPiso = new javax.swing.JTextField();
        jButtonAlta = new javax.swing.JButton();
        jLabelPosibleError = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelJavi = new javax.swing.JLabel();
        jLabelLogoP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREAR EMPLEADOS");

        jPanel1.setLayout(new java.awt.GridLayout(16, 2, 10, 10));

        jLabelid.setText("   DNI*");
        jPanel1.add(jLabelid);
        jPanel1.add(jTextDNI_NIE);

        jLabel2.setText("   Nombre*");
        jPanel1.add(jLabel2);
        jPanel1.add(jTextFieldNombre);

        jLabel3.setText("   Apellido1 *");
        jPanel1.add(jLabel3);
        jPanel1.add(jTextFieldApellido1);

        jLabelApellido2.setText("   Apellido2");
        jPanel1.add(jLabelApellido2);
        jPanel1.add(jTextFieldApellido2);

        jLabelFechaAlta.setText("   Fecha Nacimiento*");
        jPanel1.add(jLabelFechaAlta);

        jSpinnerFechaAlt.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFechaAlt.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFechaAlt, "dd/MM/yy"));
        jPanel1.add(jSpinnerFechaAlt);

        jLabelUsuario.setText("   Usuario*");
        jPanel1.add(jLabelUsuario);
        jPanel1.add(jTextFieldUsuario);

        jLabelContraseña1.setText("   Contraseña*");
        jPanel1.add(jLabelContraseña1);
        jPanel1.add(jTContraseña1);

        jLabelContraseña2.setText("   Confirmar contraseña*");
        jPanel1.add(jLabelContraseña2);
        jPanel1.add(jTContraseña2);

        jLabelRol.setText("   Rol*");
        jPanel1.add(jLabelRol);

        jComboBoxROL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "recepcionista", "servicio" }));
        jComboBoxROL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxROLItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxROL);

        jLabelCorreo.setText("   Correo*");
        jPanel1.add(jLabelCorreo);
        jPanel1.add(jTextFieldCorreo);

        jLabelTelefono.setText("   Telefono*");
        jPanel1.add(jLabelTelefono);
        jPanel1.add(jTextFieldTelefono);

        jLabelNacionalidad.setText("   Nacionalidad*");
        jPanel1.add(jLabelNacionalidad);

        jComboBoxNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Española", "Francesa", "Italiana", "Alemana", "Portuguesa", "Británica", "Estadounidense", "Canadiense", "Mexicana", "Argentina", "Brasileña", "Colombiana", "Peruana", "Chilena", "Venezolana", "China", "Japonesa", "Coreana", "India", "Marroquí", "Argelina", "Egipcia", "Rusa", "Ucraniana", "Polaca", "Rumana", "Neerlandesa", "Sueca", "Noruega", "Australiana", "Otra" }));
        jPanel1.add(jComboBoxNacionalidad);

        jLabelPais.setText("   País*");
        jPanel1.add(jLabelPais);

        jComboBoxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPaisActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxPais);

        jLabelCalle_numero.setText("   Numero de calle*");
        jPanel1.add(jLabelCalle_numero);
        jPanel1.add(jTextFieldCalle_Numero);

        jLabelPoblacion.setText("   Población*");
        jPanel1.add(jLabelPoblacion);
        jPanel1.add(jTextFieldPoblacion);

        jLabelPiso.setText("   Piso");
        jPanel1.add(jLabelPiso);
        jPanel1.add(jTextFieldPiso);

        jButtonAlta.setText("Aceptar");
        jButtonAlta.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jLabelPosibleError.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPosibleError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Todos los datos con * son OBLIGATORIOS");

        jLabelJavi.setText("Javier Dapena");

        jLabelLogoP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoHoteliaMuyChiquito.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabelPosibleError, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelLogoP))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabelJavi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLogoP)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPosibleError, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLabelJavi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Boton para Crear un Empleado
     *
     * @param evt
     */
    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed

        Date fecha = (Date) jSpinnerFechaAlt.getValue();
        String rol = (String) jComboBoxROL.getSelectedItem();
        if (jTextDNI_NIE.getText().trim().isEmpty() || c.consultaIdEmpleado(jTextDNI_NIE.getText().trim())) {
            jLabelPosibleError.setText("El DNI/NIE ya existe o está vacío");
            return;
        }
        if (jTextFieldNombre.getText().trim().isEmpty()
                || jTextFieldApellido1.getText().trim().isEmpty()
                || jTextFieldUsuario.getText().trim().isEmpty()
                || jTContraseña1.getText().trim().isEmpty()
                || jTContraseña2.getText().trim().isEmpty()
                || jTextFieldCorreo.getText().trim().isEmpty()
                || jTextFieldTelefono.getText().trim().isEmpty()
                || jTextFieldCalle_Numero.getText().trim().isEmpty()
                || jTextFieldPoblacion.getText().trim().isEmpty()) {
            jLabelPosibleError.setText("Rellena todos los datos obligatorios (*)");
            return;
        }
        if (!jTContraseña1.getText().equals(jTContraseña2.getText())) {
            jLabelPosibleError.setText("Las contraseñas no coinciden");
            return;
        }
        String correo = jTextFieldCorreo.getText().trim();
        if (!correo.matches("^[^@]+@[^@]+\\.[^@]+$")) {
            jLabelPosibleError.setText("Correo electrónico no válido");
            return;
        }
        String telefono = jTextFieldTelefono.getText().trim();
        if (!telefono.matches("^\\+?[0-9]{7,15}$")) {
            jLabelPosibleError.setText("Teléfono no válido (7-15 dígitos, puede empezar por +)");
            return;
        }
        String contraseniaHas = Seguridad.hashPassword(jTContraseña1.getText());
        Empleado empleado = new Empleado(
                jTextDNI_NIE.getText().trim(),
                jTextFieldNombre.getText().trim(),
                jTextFieldApellido1.getText().trim(),
                jTextFieldApellido2.getText().trim(),
                fecha,
                jTextFieldUsuario.getText().trim(),
                contraseniaHas, rol, correo, telefono,
                jComboBoxNacionalidad.getSelectedItem().toString(),
                jComboBoxPais.getSelectedItem().toString(),
                jTextFieldCalle_Numero.getText().trim(),
                jTextFieldPoblacion.getText().trim(),
                jTextFieldPiso.getText().trim());
        boolean prueba = c.insertEmpleado(empleado);
        jLabelPosibleError.setText(!prueba ? "Error al crear el empleado" : "Empleado creado con éxito");
    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void jComboBoxROLItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxROLItemStateChanged
    }//GEN-LAST:event_jComboBoxROLItemStateChanged

    private void jComboBoxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPaisActionPerformed
    }//GEN-LAST:event_jComboBoxPaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatCobalt2IJTheme.setup();

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogCrearEmpleado dialog = new JDialogCrearEmpleado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JComboBox<String> jComboBoxNacionalidad;
    private javax.swing.JComboBox<String> jComboBoxPais;
    private javax.swing.JComboBox<String> jComboBoxROL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelCalle_numero;
    private javax.swing.JLabel jLabelContraseña1;
    private javax.swing.JLabel jLabelContraseña2;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelFechaAlta;
    private javax.swing.JLabel jLabelJavi;
    private javax.swing.JLabel jLabelLogoP;
    private javax.swing.JLabel jLabelNacionalidad;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelPiso;
    private javax.swing.JLabel jLabelPoblacion;
    private javax.swing.JLabel jLabelPosibleError;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelid;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerFechaAlt;
    private javax.swing.JTextField jTContraseña1;
    private javax.swing.JTextField jTContraseña2;
    private javax.swing.JTextField jTextDNI_NIE;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldCalle_Numero;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPiso;
    private javax.swing.JTextField jTextFieldPoblacion;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
