/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.ConexionBBDD;
import Controlador.ReservaDAO;
import Modelo.Empleado;
import Modelo.Reserva;
import com.formdev.flatlaf.intellijthemes.FlatCobalt2IJTheme;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.sql.*;
import java.util.List;
import java.util.regex.PatternSyntaxException;
import javax.swing.RowFilter;

/**
 *
 * @author DAM2Alu3
 */
public class JDialogReservaTable extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogReservaTable.class.getName());    

    // objetos globales
    DefaultTableModel dtm;
    TableRowSorter<TableModel> order;
    ReservaDAO c = new ReservaDAO();

    public void cargaInicial() throws SQLException {
        dtm.setRowCount(0);
        c.selectTodasReservas(dtm);
        jTableReservas.setModel(dtm);

    }

    public void configuraColumna(int ncol, int ancho) {
        TableColumn columna = jTableReservas.getColumnModel().getColumn(ncol);
        columna.setPreferredWidth(ancho);
    }

    /**
     * Creates new form 
     */
    public JDialogReservaTable(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        setTitle("Reservas");
        dtm = new DefaultTableModel();
        jTableReservas.setModel(dtm);
        dtm.setColumnIdentifiers(Reserva.getColumnas());
        c.selectTodasReservas(dtm);

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width, screenSize.height);
        this.setLocation(0, 0);
        cargaInicial();
        order = new TableRowSorter<>(dtm);
        jTableReservas.setRowSorter(order);
        configuraColumna(0, 5);
        configuraColumna(4, 30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReservas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonEditar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDNICliente = new javax.swing.JTextField();
        jButtonCrear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();
        jLabelLogoM = new javax.swing.JLabel();
        jLabelJulia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1059, 700));

        jTableReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableReservas);

        jButtonEditar.setText("EDITAR");
        jButtonEditar.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEditar);

        jButtonEliminar.setText("ELIMINAR");
        jButtonEliminar.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEliminar);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DNI cliente");
        jLabel1.setPreferredSize(new java.awt.Dimension(90, 40));
        jPanel2.add(jLabel1);

        jTextFieldDNICliente.setPreferredSize(new java.awt.Dimension(255, 40));
        jTextFieldDNICliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDNIClienteKeyReleased(evt);
            }
        });
        jPanel2.add(jTextFieldDNICliente);

        jButtonCrear.setText("CREAR");
        jButtonCrear.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCrear);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("RESERVAS");

        jLabelError.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jLabelLogoM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoHotelia100x100.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addGap(0, 943, Short.MAX_VALUE)
                    .addComponent(jLabelLogoM)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(31, 31, 31))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelLogoM)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabelJulia.setText("Julia Castarlenas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelJulia, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelJulia)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt
     */
    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        
        if (jTableReservas.getSelectedRowCount() != 1) {
        jLabelError.setText("Selecciona exactamente una fila");
        return;
    }

    try {
        int filaModelo = jTableReservas.convertRowIndexToModel(
                jTableReservas.getSelectedRow());

        int idReserva = Integer.parseInt(
                jTableReservas.getModel()
                        .getValueAt(filaModelo, 0)
                        .toString());

        JDialogReserva jder = new JDialogReserva(null, true);

        jder.setIdReserva(idReserva);

        jder.setVisible(true);

        dtm.setRowCount(0);
        c.selectTodasReservas(dtm);

        jLabelError.setText("");

    } catch (SQLException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_jButtonEditarActionPerformed

    /**
     * Eliminamos de 1 en 1 las reservas
     *
     * @param evt
     */
    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        if (jTableReservas.getSelectedRowCount() == 1) {

            // recojo el indice real de la tabla
            int filaModelo = jTableReservas.convertRowIndexToModel(jTableReservas.getSelectedRow());

            // id (columna 0)
            int id = (int) jTableReservas.getModel().getValueAt(filaModelo, 0);

            // Compruebo si se ha borrado 
            if (c.eliminarReserva(dtm, id) < 1) {
                jLabelError.setText("No se ha podido borrar ninguna reserva");
            } else {
                // Quitar del modelo de tabla
                dtm.removeRow(filaModelo);
            }// end if comprobacion
        } else {
            jLabelError.setText("Selecciona exactamente una fila");
        }// end if
        // Reseteo el dtm para luego hacer el select de todos y asi tenerlo actualizado y que no se me duplique la informacion
        dtm.setRowCount(0);
        c.selectTodasReservas(dtm);

    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        try {
            // TODO add your handling code here:
            JDialogReserva jdr = new JDialogReserva(null, true);
            
            // hago visible el jframe
            jdr.setVisible(true);
            
            // Reseteo el dtm para luego hacer el select de todos y asi tenerlo actualizado y que no se me duplique la informacion
            dtm.setRowCount(0);
            c.selectTodasReservas(dtm);
        } catch (SQLException ex) {
            System.getLogger(JDialogReservaTable.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }//GEN-LAST:event_jButtonCrearActionPerformed

    

/**
 * Metodo para gestionar y buscar por nombre y apellido
 */
private void busqueda() {
    try {
        // Hago un array de objetos (de la fila)
        List<RowFilter<Object,Object>> filtros = new ArrayList<>();

        // Si el campo nombre no está vacío, creamos el filtro para la columna 1 
        if (!jTextFieldDNICliente.getText().trim().isEmpty()) {
            filtros.add(RowFilter.regexFilter(jTextFieldDNICliente.getText().trim(), 1));
        }
           
        RowFilter<Object,Object> rf = RowFilter.andFilter(filtros);

        order.setRowFilter(rf);

    } catch (PatternSyntaxException pse) {
        System.out.println("Bad regex pattern");
    }
}
    private void jTextFieldDNIClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIClienteKeyReleased
        busqueda();
    }//GEN-LAST:event_jTextFieldDNIClienteKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatCobalt2IJTheme.setup();

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogReservaTable dialog = null;
                try {
                    dialog = new JDialogReservaTable(new javax.swing.JFrame(), true);
                } catch (SQLException ex) {
                    System.getLogger(JDialogReservaTable.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelJulia;
    private javax.swing.JLabel jLabelLogoM;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableReservas;
    private javax.swing.JTextField jTextFieldDNICliente;
    // End of variables declaration//GEN-END:variables
}
