/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;


import Controlador.ClienteDAO;
import Controlador.ConexionBBDD;
import Controlador.FacturaDAO;
import Controlador.ReservaDAO;
import Modelo.Cliente;
import Modelo.Factura;
import Modelo.Reserva;
import com.formdev.flatlaf.intellijthemes.FlatCobalt2IJTheme;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DAM2Alu3
 */
public class JDialogEditarFactura extends javax.swing.JDialog {
    private JTable JDialogFacturaTable;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogEditarFactura.class.getName());
    private FacturaDAO f = new FacturaDAO();
    private ReservaDAO r = new ReservaDAO();
    private ClienteDAO c = new ClienteDAO();
    /**
     * Creates new form
     */
    
    JFrameLogin jframepadre;
    private int idFactura;
    
    public JDialogEditarFactura(java.awt.Frame parent, boolean modal, JTable tabla) {
        super(parent, modal);
        initComponents();
        this.JDialogFacturaTable = tabla;
        setTitle("Factura");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelClientes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelDNI = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jSpinnerFecha_reserva = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldObservaciones = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxMetodoPago = new javax.swing.JComboBox<>();
        jLabelEstado = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDescuento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSubtotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jButtonEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelClientes.setText("FACTURA");

        jPanel1.setLayout(new java.awt.GridLayout(8, 2, 10, 10));

        jLabelDNI.setText("DNI cliente*");
        jPanel1.add(jLabelDNI);
        jPanel1.add(jTextFieldDNI);

        jLabelNombre.setText("Fecha y hora emisión de factura");
        jPanel1.add(jLabelNombre);

        jSpinnerFecha_reserva.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFecha_reserva.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFecha_reserva, "dd/MM/yyyy HH:mm:ss"));
        jSpinnerFecha_reserva.setEnabled(false);
        jPanel1.add(jSpinnerFecha_reserva);

        jLabel4.setText("Observaciones*");
        jPanel1.add(jLabel4);

        jTextFieldObservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldObservacionesActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldObservaciones);

        jLabel6.setText("Metodo de pago*");
        jPanel1.add(jLabel6);

        jComboBoxMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta" }));
        jComboBoxMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMetodoPagoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxMetodoPago);

        jLabelEstado.setText("Estado*");
        jPanel1.add(jLabelEstado);

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Pagado" }));
        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxEstado);

        jLabel5.setText("Descuento*");
        jPanel1.add(jLabel5);
        jPanel1.add(jTextFieldDescuento);

        jLabel7.setText("Subtotal");
        jPanel1.add(jLabel7);

        jTextFieldSubtotal.setEditable(false);
        jTextFieldSubtotal.setEnabled(false);
        jTextFieldSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSubtotalActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldSubtotal);

        jLabel3.setText("Total");
        jPanel1.add(jLabel3);

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setEnabled(false);
        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTotal);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonEditar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23)
                .addComponent(jButtonEditar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        try {
            
            int filaSeleccionada = JDialogFacturaTable.getSelectedRow();

            if (filaSeleccionada == -1) {
                jLabel1.setText("Selecciona una factura");
                return;
            }
            
            int filaModelo = JDialogFacturaTable.convertRowIndexToModel(filaSeleccionada);

            
            idFactura = Integer.parseInt(((DefaultTableModel) JDialogFacturaTable.getModel()).getValueAt(filaModelo, 0).toString());

            Factura facturaEd = f.buscaFacturas(idFactura);

            facturaEd.setMetodo_pago(jComboBoxMetodoPago.getSelectedItem().toString());

            facturaEd.setEstado(jComboBoxEstado.getSelectedItem().toString());

            int descuento;
            try {
                descuento = Integer.parseInt(jTextFieldDescuento.getText());
            } catch (NumberFormatException e) {
                jLabel1.setText("Descuento inválido");
                return;
            }

            facturaEd.setDescuento(descuento);
            
            facturaEd.setObservacion(jTextFieldObservaciones.getText());

            
            if (f.editarFactura(facturaEd) >= 1) {

                f.recalcularFactura(facturaEd.getIdFactura());

                jLabel1.setText("Factura actualizada");
                dispose();
            } else {
                jLabel1.setText("No se pudo editar");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            jLabel1.setText("Error al editar");
        }
        
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jTextFieldObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldObservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldObservacionesActionPerformed

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    private void jComboBoxMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMetodoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMetodoPagoActionPerformed

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

    private void jTextFieldSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSubtotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatCobalt2IJTheme.setup();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxMetodoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerFecha_reserva;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldDescuento;
    private javax.swing.JTextField jTextFieldObservaciones;
    private javax.swing.JTextField jTextFieldSubtotal;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables

    public void setIdFactura(int idFactura) {
        this.idFactura= idFactura;
    
    }
}
