/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.HabitacionDAO;
import com.formdev.flatlaf.intellijthemes.FlatCobalt2IJTheme;
import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 * JDialog para crear nuevas habitaciones.
 * Valida campos y calcula precio_publico automáticamente dependiendo
 * de la forma elegida de precio.
 * 
 * @author DAM2Alu16
 */
public class JDialogAnadirHabitaciones extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = 
        java.util.logging.Logger.getLogger(JDialogAnadirHabitaciones.class.getName());

    //el margen es para cuando se elige el precio especial 😊
    private static final double MARGEN = 0.30;
    private static final double IVA = 0.21;
    private HabitacionDAO habitacionDAO;

    public JDialogAnadirHabitaciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.habitacionDAO = new HabitacionDAO();
        initComponents();
        initListeners();
    }

    private void initListeners() {
        sPrecioB.addChangeListener(e -> actualizarPrecioPublico());
        jCheckBox1.addActionListener(e -> actualizarPrecioPublico());
        actualizarPrecioPublico();
    }

    private void actualizarPrecioPublico() {
        double base = ((Number) sPrecioB.getValue()).doubleValue();
        double publico = jCheckBox1.isSelected()
            ? base * (1 + MARGEN) * (1 + IVA)
            : base;
    }
    // Metodo que se asegura que puede guardar cambios y si puede lsos guarda
    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {                                               
        List<String> errores = new ArrayList<>();

        String numStr = etNumHab.getText().trim();
        if (numStr.isEmpty()) {
            errores.add("El numero de la habitacion no puede ser nulo");
        } else {
            try {
                int num = Integer.parseInt(numStr);
                if (num <= 0) errores.add("El numero debe ser mayor que 0");
            } catch (NumberFormatException e) {
                errores.add("El numero debe ser un valor numerico");
            }
        }

        double precioBase = ((Number) sPrecioB.getValue()).doubleValue();
        if (precioBase <= 0) {
            errores.add("El precio base debe ser mayor que 0");
        }

        if (!errores.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, 
                "Corrija los errores:\n\n• " + String.join("\n• ", errores),
                "Errores de validacion",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Guardar
        try {
            int numero = Integer.parseInt(numStr);
            String tipo = (String) cbTipo.getSelectedItem();
            int capacidad = (Integer) sCapacidad.getValue();
            String estado = (String) cbEstado.getSelectedItem();
            double precioPublico = jCheckBox1.isSelected()
                ? precioBase * (1 + MARGEN) * (1 + IVA)
                : precioBase;

            habitacionDAO.insertarHabitacion(numero, tipo, capacidad, precioBase, precioPublico, estado);

            JOptionPane.showMessageDialog(rootPane, 
                "Habitacion añadida correctamente\n" +
                "Precio publico calculado: " + String.format("%.2f", precioPublico) + " €");
            dispose();

        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error guardando habitacion", e);
            JOptionPane.showMessageDialog(rootPane, 
                "Error al guardar: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                                
        dispose();
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        etNumHab = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        sCapacidad = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        sPrecioB = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabelLogoP = new javax.swing.JLabel();
        jLabelSergio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new java.awt.GridLayout(7, 2, 10, 10));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Número de habitación");
        jPanel2.add(jLabel1);
        jPanel2.add(etNumHab);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Tipo");
        jPanel2.add(jLabel2);

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Duplex", "Junior", "Presidencial" }));
        jPanel2.add(cbTipo);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Capacidad");
        jPanel2.add(jLabel3);
        jPanel2.add(sCapacidad);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Precio base");
        jPanel2.add(jLabel4);
        jPanel2.add(sPrecioB);
        jPanel2.add(jLabel7);

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("¿Usar formulas de precio?");
        jPanel2.add(jCheckBox1);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Estado");
        jPanel2.add(jLabel5);

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Reparacion" }));
        jPanel2.add(cbEstado);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAceptar);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CREAR HABITACIÓN");

        jLabelLogoP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoHoteliaMuyChiquito.png"))); // NOI18N

        jLabelSergio.setText("Sergio Vasilev");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSergio, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(405, Short.MAX_VALUE)
                    .addComponent(jLabelLogoP)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSergio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelLogoP)
                    .addContainerGap(342, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        FlatCobalt2IJTheme.setup();

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogAnadirHabitaciones dialog = new JDialogAnadirHabitaciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JTextField etNumHab;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelLogoP;
    private javax.swing.JLabel jLabelSergio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner sCapacidad;
    private javax.swing.JSpinner sPrecioB;
    // End of variables declaration//GEN-END:variables
}