/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.ClienteDAO;
import Controlador.ConexionBBDD;
import Controlador.HabitacionDAO;
import Controlador.ServicioDAO;
import com.formdev.flatlaf.intellijthemes.FlatCobalt2IJTheme;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JComboBox;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.ooxml.JRXlsxExporter;
import net.sf.jasperreports.export.SimpleExporterInput;
import net.sf.jasperreports.export.SimpleOutputStreamExporterOutput;
import net.sf.jasperreports.view.JasperViewer;
import java.io.InputStream;

/**
 *
 * @author DAM2Alu4
 */
public class JDialogEstadisticas extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogEstadisticas.class.getName());
    // variables
    private ClienteDAO c = new ClienteDAO();
    private HabitacionDAO h = new HabitacionDAO();
    private ServicioDAO s= new ServicioDAO();
    /**
     * Creates new form JDialogEstadisticas
     */
    public JDialogEstadisticas(java.awt.Frame parent, boolean modal) {
        super(parent, false);
        initComponents();
        setTitle("Estadisticas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jBoxCliente = new javax.swing.JComboBox<>();
        ActualizarCliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jBoxHabitacion = new javax.swing.JComboBox<>();
        ActualizarHabitacion = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jBoxServicio = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        ActualizarEmpleado = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        InformeCliente1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        InformeHabitacion1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        InformeEmpleado1 = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESTADISTICAS");

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("CLIENTES");
        jPanel2.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 semana", "1 mes", "6 meses", "1 año" }));
        jPanel2.add(jBoxCliente, java.awt.BorderLayout.LINE_END);

        ActualizarCliente.setText("Actualizar");
        ActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(ActualizarCliente, java.awt.BorderLayout.PAGE_END);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Clientes", jPanel2);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("HABITACIONES");
        jPanel4.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jBoxHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 semana", "1 mes", "6 meses", "1 año" }));
        jPanel4.add(jBoxHabitacion, java.awt.BorderLayout.LINE_END);

        ActualizarHabitacion.setText("Actualizar");
        ActualizarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarHabitacionActionPerformed(evt);
            }
        });
        jPanel4.add(ActualizarHabitacion, java.awt.BorderLayout.PAGE_END);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jPanel4.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Habitaciones", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("EMPLEADOS");
        jPanel5.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jBoxServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 semana", "1 mes", "6 meses", "1 año" }));
        jPanel5.add(jBoxServicio, java.awt.BorderLayout.LINE_END);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jPanel5.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        ActualizarEmpleado.setText("Actualizar");
        ActualizarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarEmpleadoActionPerformed(evt);
            }
        });
        jPanel5.add(ActualizarEmpleado, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Empleados", jPanel5);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("CLIENTES");
        jPanel3.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        InformeCliente1.setText("Generar informe de clientes");
        InformeCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformeCliente1ActionPerformed(evt);
            }
        });
        jPanel3.add(InformeCliente1, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Clientes", jPanel3);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 204));
        jLabel7.setText("FACTURAS");
        jPanel6.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        InformeHabitacion1.setText("Generar informe de las facturas");
        InformeHabitacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformeHabitacion1ActionPerformed(evt);
            }
        });
        jPanel6.add(InformeHabitacion1, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Facturas", jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 204));
        jLabel8.setText("EMPLEADOS");
        jPanel7.add(jLabel8, java.awt.BorderLayout.PAGE_START);

        InformeEmpleado1.setText("Generar informe de los empleados");
        InformeEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformeEmpleado1ActionPerformed(evt);
            }
        });
        jPanel7.add(InformeEmpleado1, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Empleados", jPanel7);

        jTabbedPane1.addTab("Informes", jTabbedPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(416, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(74, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Habitaciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Con este metodo, recojo la opcion que haya seleccionado el usuario Cojo
     * el dia de goy y lo paso dependiendo del tiempo seleccionado
     *
     * @param opcion
     * @return
     */
    private LocalDate obtenerFechaLimite(String opcion) {

        LocalDate hoy = LocalDate.now();
        switch (opcion) {
            case "1 semana":
                return hoy.minusWeeks(1);
            case "1 mes":
                return hoy.minusMonths(1);
            case "6 meses":
                return hoy.minusMonths(6);
            case "1 año":
                return hoy.minusYears(1);
            default:
                return hoy.minusMonths(1); // por defecto 1 mes
        }
    }// end obtenerFechaLimite

// boton Actualizar
    private void ActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarClienteActionPerformed

        String opcion = (String) jBoxCliente.getSelectedItem();
        LocalDate fechaLimite = obtenerFechaLimite(opcion);

        int totalClientes = 0;
        try {
            totalClientes = c.getTotalClientes(fechaLimite);
        } catch (SQLException ex) {
            System.getLogger(JDialogEstadisticas.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

        jTextArea1.setText("Total clientes en los últimos " + opcion + ": " + totalClientes);


    }//GEN-LAST:event_ActualizarClienteActionPerformed

    private void ActualizarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarHabitacionActionPerformed
        try {
            String opcion = (String) jBoxHabitacion.getSelectedItem();
            LocalDate fechaLimite = obtenerFechaLimite(opcion);

            int totalHabitaciones;

            totalHabitaciones = h.getTotalHabitaciones(fechaLimite);

            String detalleTipos = h.getCantidadHabitacionesPorTipoString(fechaLimite);

            String resultado = "Total habitaciones reservadas en los últimos " + opcion + ": " + totalHabitaciones + "\n\n"
                    + "Cantidad por tipo de habitación:\n" + detalleTipos;

            jTextArea2.setText(resultado);
        } catch (SQLException ex) {
            System.getLogger(JDialogEstadisticas.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_ActualizarHabitacionActionPerformed

    private void ActualizarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarEmpleadoActionPerformed
        try {
            String opcion = (String) jBoxServicio.getSelectedItem();
            LocalDate fechaLimite = obtenerFechaLimite(opcion);

            int totalServicios = s.getTotalServicios(fechaLimite);
            String detalleServicios = s.getCantidadServiciosPorNombreString(fechaLimite);

            String resultado = "Total servicios usados en los últimos " + opcion + ": " + totalServicios + "\n\n"
                    + "Cantidad por servicio:\n" + detalleServicios;

            jTextArea3.setText(resultado);
        } catch (SQLException ex) {
            System.getLogger(JDialogEstadisticas.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_ActualizarEmpleadoActionPerformed

    private void InformeCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformeCliente1ActionPerformed
        // TODO add your handling code here:
        
         try {
            ConexionBBDD nueva = new ConexionBBDD();

            String fileJasper = "src/reports/prueba2.jasper";
            JasperPrint print
                    = JasperFillManager.fillReport(fileJasper, null, nueva.getConnection());
            JasperViewer jviewer = new JasperViewer(print, false);
            jviewer.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
         } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_InformeCliente1ActionPerformed

    private void InformeHabitacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformeHabitacion1ActionPerformed
        // TODO add your handling code here:
        try {
            ConexionBBDD nueva = new ConexionBBDD();

            String fileJasper = "src/reports/infFacturas.jasper";
            JasperPrint print
                    = JasperFillManager.fillReport(fileJasper, null, nueva.getConnection());
            JasperViewer jviewer = new JasperViewer(print, false);
            jviewer.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_InformeHabitacion1ActionPerformed

    private void InformeEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformeEmpleado1ActionPerformed
        // TODO add your handling code here:
        try {
            ConexionBBDD nueva = new ConexionBBDD();

            String fileJasper = "src/reports/Empleado.jasper";
            JasperPrint print
                    = JasperFillManager.fillReport(fileJasper, null, nueva.getConnection());
            JasperViewer jviewer = new JasperViewer(print, false);
            jviewer.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_InformeEmpleado1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatCobalt2IJTheme.setup();

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogEstadisticas dialog = new JDialogEstadisticas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarCliente;
    private javax.swing.JButton ActualizarEmpleado;
    private javax.swing.JButton ActualizarHabitacion;
    private javax.swing.JButton InformeCliente1;
    private javax.swing.JButton InformeEmpleado1;
    private javax.swing.JButton InformeHabitacion1;
    private javax.swing.JComboBox<String> jBoxCliente;
    private javax.swing.JComboBox<String> jBoxHabitacion;
    private javax.swing.JComboBox<String> jBoxServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
