/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;


import Controlador.ClienteDAO;
import Controlador.ConexionBBDD;
import Controlador.FacturaDAO;
import Controlador.HabitacionDAO;
import Controlador.ReservaDAO;
import Controlador.ServicioDAO;
import Modelo.Cliente;
import Modelo.Factura;
import Modelo.Habitacion;
import Modelo.Reserva;
import Modelo.Servicio;
import com.formdev.flatlaf.intellijthemes.FlatCobalt2IJTheme;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;


/**
 *
 * @author DAM2Alu3
 */
public class JDialogReserva extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogReserva.class.getName());
    private ReservaDAO r = new ReservaDAO();
    private HabitacionDAO h = new HabitacionDAO();
    private ServicioDAO s = new ServicioDAO();
    private FacturaDAO f = new FacturaDAO();
    private ClienteDAO ClienteDAO = new ClienteDAO();
    /**
     * Creates new form
     */
    
    JFrameLogin jframepadre;
    private JTable jTableClientes;
    private Integer idReserva;
    
    private void cargarServicios() throws SQLException {
        ResultSet rs = null;
        ResultSet rs2 = null;
        try {
            ConexionBBDD c = new ConexionBBDD();
            Connection conexion = c.getConnection();
            rs = s.todosServicios();
            rs2 = h.todasHabitacionesLibres();
            
            jComboBoxReserva.removeAllItems(); // limpiamos combo
            jComboBoxReserva1.removeAllItems(); // limpiamos combo
            jComboBoxReserva.addItem("Ninguno");
            jComboBoxReserva1.addItem("Ninguno");

            while (rs.next()) {
                String nombre = rs.getString("nombre");
                
                jComboBoxReserva.addItem(nombre);
            }
            while (rs2.next()){
                String hab = rs2.getString("tipo");
                jComboBoxReserva1.addItem(hab);
            }
            
        } catch (SQLException ex) {
            System.getLogger(JDialogReserva.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } finally {
            if (rs != null) rs.close();
            if (rs2 != null) rs2.close();
        }

}
    
    public JDialogReserva(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        jSpinnerFecha_reserva.setValue(new Date());
        cargarServicios();
        setTitle("Reserva");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelClientes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelDNI = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxReserva1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxReserva = new javax.swing.JComboBox<>();
        jLabelFecha_nac = new javax.swing.JLabel();
        jSpinnerFecha_inicio = new javax.swing.JSpinner();
        jLabelFecha_nac1 = new javax.swing.JLabel();
        jSpinnerFecha_fin = new javax.swing.JSpinner();
        jLabelApellido2 = new javax.swing.JLabel();
        jSpinnerNPersonas = new javax.swing.JSpinner();
        jLabelNombre = new javax.swing.JLabel();
        jSpinnerFecha_reserva = new javax.swing.JSpinner();
        jLabelApelliod1 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jButtonCrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelClientes.setText("RESERVA");

        jPanel1.setLayout(new java.awt.GridLayout(8, 2, 10, 10));

        jLabelDNI.setText("DNI cliente*");
        jPanel1.add(jLabelDNI);
        jPanel1.add(jTextFieldDNI);

        jLabel2.setText("Reserva habitacion");
        jPanel1.add(jLabel2);

        jComboBoxReserva1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxReserva1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxReserva1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxReserva1);

        jLabel3.setText("Reserva servicio");
        jPanel1.add(jLabel3);

        jComboBoxReserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxReservaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxReserva);

        jLabelFecha_nac.setText("Fecha de inicio*");
        jPanel1.add(jLabelFecha_nac);

        jSpinnerFecha_inicio.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));
        jSpinnerFecha_inicio.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFecha_inicio, "dd/MM/yyyy"));
        jPanel1.add(jSpinnerFecha_inicio);

        jLabelFecha_nac1.setText("Fecha de fin*");
        jPanel1.add(jLabelFecha_nac1);

        jSpinnerFecha_fin.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));
        jSpinnerFecha_fin.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFecha_fin, "dd/MM/yyyy"));
        jPanel1.add(jSpinnerFecha_fin);

        jLabelApellido2.setText("Cantidad de personas*");
        jPanel1.add(jLabelApellido2);

        jSpinnerNPersonas.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(jSpinnerNPersonas);

        jLabelNombre.setText("Fecha hora reserva");
        jPanel1.add(jLabelNombre);

        jSpinnerFecha_reserva.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFecha_reserva.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFecha_reserva, "dd/MM/yyyy HH:mm:ss"));
        jSpinnerFecha_reserva.setEnabled(false);
        jPanel1.add(jSpinnerFecha_reserva);

        jLabelApelliod1.setText("Estado*");
        jPanel1.add(jLabelApelliod1);

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aceptado", "Cancelado" }));
        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxEstado);

        jButtonCrear.setText("Crear");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCrear)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCrear)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        try {

            Cliente cliente = ClienteDAO.buscaCliente(jTextFieldDNI.getText().trim());

            if(cliente == null){

                JOptionPane.showMessageDialog(
                    this,
                    "El cliente no existe. Debe crearlo primero."
                );

                JDialogCliente dialog =
                    new JDialogCliente(null, true, jTableClientes);

                dialog.setVisible(true);

                return;
            }

            Factura factura = f.buscaFactura(jTextFieldDNI.getText());

            int idFactura;
            Integer idServicio = null;
            Integer idHabitacion = null;

            if (factura == null) {
                idFactura = f.crearFacturaPendiente(jTextFieldDNI.getText());
            } else {
                idFactura = factura.getIdFactura();
            }

            if(jComboBoxReserva.getSelectedIndex() != 0){
                idServicio = s.buscarServicioId(
                    jComboBoxReserva.getSelectedItem().toString()
                );
            }

            if(jComboBoxReserva1.getSelectedIndex() != 0){
                idHabitacion = h.buscarHabitacionId(
                    jComboBoxReserva1.getSelectedItem().toString()
                );
            }

            Reserva nuevo = new Reserva(
                    idServicio,
                    idHabitacion,
                    idFactura,
                    (int) jSpinnerNPersonas.getValue(),
                    jTextFieldDNI.getText(),
                    jComboBoxEstado.getSelectedItem().toString(),
                    (Date) jSpinnerFecha_inicio.getValue(),
                    (Date) jSpinnerFecha_fin.getValue(),
                    (Date) jSpinnerFecha_reserva.getValue()
            );

            if(idServicio == null && idHabitacion == null){

                JOptionPane.showMessageDialog(
                    this,
                    "Debe seleccionar un servicio o una habitación"
                );

                return;
            }

            int resultado;

            // CREAR
            if (idReserva == null) {

                resultado = r.insertaReserva(nuevo);

                if (resultado >= 1) {
                    jLabel1.setText("Creado con exito");
                } else {
                    jLabel1.setText("No se ha creado");
                }

            // EDITAR
            } else {

                resultado = r.editarReserva(nuevo, idReserva);

                if (resultado >= 1) {
                    jLabel1.setText("Editado con exito");
                } else {
                    jLabel1.setText("No se ha editado");
                }
            }

            f.recalcularFactura(idFactura);

            dispose();

        } catch (SQLException ex) {
            System.getLogger(JDialogReserva.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

    private void jComboBoxReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxReservaActionPerformed

    private void jComboBoxReserva1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxReserva1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxReserva1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatCobalt2IJTheme.setup();

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    JDialogReserva dialog = new JDialogReserva(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (SQLException ex) {
                    System.getLogger(JDialogReserva.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxReserva;
    private javax.swing.JComboBox<String> jComboBoxReserva1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelApelliod1;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelFecha_nac;
    private javax.swing.JLabel jLabelFecha_nac1;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerFecha_fin;
    private javax.swing.JSpinner jSpinnerFecha_inicio;
    private javax.swing.JSpinner jSpinnerFecha_reserva;
    private javax.swing.JSpinner jSpinnerNPersonas;
    private javax.swing.JTextField jTextFieldDNI;
    // End of variables declaration//GEN-END:variables

    public void setIdReserva(int idReserva) throws SQLException {
        cargarServicios();
        this.idReserva = idReserva;
        Reserva reserva = r.buscaReservaId(idReserva);        
        cargarDatosReserva(reserva);

    }

    private void cargarDatosReserva(Reserva reserva) throws SQLException {
        jTextFieldDNI.setText(reserva.getIdCliente());
        jSpinnerNPersonas.setValue(reserva.getCantidad_personas());
        jComboBoxEstado.setSelectedItem(reserva.getEstado());
        
        if (reserva.getIdServicio() != null) {

            Servicio servicio =
                    s.buscarServicioPorId(
                            reserva.getIdServicio()
                    );

            if (servicio != null) {

                jComboBoxReserva.setSelectedItem(
                        servicio.getNombre()
                );
            }
        }
        
        if (reserva.getIdHabitacion() != null) {

            Habitacion habitacion =
                    h.buscarHabitacionPorId(
                            reserva.getIdHabitacion()
                    );

            if (habitacion != null) {

                jComboBoxReserva1.setSelectedItem(
                        habitacion.getTipo()
                );
            }
        }
       
        jSpinnerFecha_inicio.setValue(reserva.getFecha_inicio());
        jSpinnerFecha_fin.setValue(reserva.getFecha_fin());
        jSpinnerFecha_reserva.setValue(reserva.getFecha_hora_reserva());    
    }

}
