/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.HabitacionDAO;
import com.formdev.flatlaf.intellijthemes.FlatCobalt2IJTheme;
import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Diálogo para crear nuevas habitaciones.
 * Valida campos y calcula precio_publico automáticamente.
 * 
 * @author DAM2Alu16
 */
public class JDialogAnadirHabitaciones extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = 
        java.util.logging.Logger.getLogger(JDialogAnadirHabitaciones.class.getName());

    private static final double MARGEN = 0.30;
    private static final double IVA = 0.21;
    private HabitacionDAO habitacionDAO;

    public JDialogAnadirHabitaciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.habitacionDAO = new HabitacionDAO();
        initComponents();
        initListeners();
    }

    private void initListeners() {
        jsPrecioB.addChangeListener(e -> actualizarPrecioPublico());
        jcbFormulas.addActionListener(e -> actualizarPrecioPublico());
        actualizarPrecioPublico();
    }

    private void actualizarPrecioPublico() {
        double base = ((Number) jsPrecioB.getValue()).doubleValue();
        double publico = jcbFormulas.isSelected()
            ? base * (1 + MARGEN) * (1 + IVA)
            : base;
    }

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {                                               
        List<String> errores = new ArrayList<>();

        String numStr = jetNumHab.getText().trim();
        if (numStr.isEmpty()) {
            errores.add("El numero de la habitacion no puede ser nulo");
        } else {
            try {
                int num = Integer.parseInt(numStr);
                if (num <= 0) errores.add("El numero debe ser mayor que 0");
            } catch (NumberFormatException e) {
                errores.add("El numero debe ser un valor numerico");
            }
        }

        double precioBase = ((Number) jsPrecioB.getValue()).doubleValue();
        if (precioBase <= 0) {
            errores.add("El precio base debe ser mayor que 0");
        }

        if (!errores.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, 
                "Corrija los errores:\n\n• " + String.join("\n• ", errores),
                "Errores de validacion",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int numero = Integer.parseInt(numStr);
            String tipo = (String) jcbTipo.getSelectedItem();
            int capacidad = (Integer) jsCapacidad.getValue();
            String estado = (String) jcbEstado.getSelectedItem();
            double precioPublico = jcbFormulas.isSelected()
                ? precioBase * (1 + MARGEN) * (1 + IVA)
                : precioBase;

            // ===== USAR HABITACIONDAO (DTO) =====
            habitacionDAO.insertarHabitacion(numero, tipo, capacidad, precioBase, precioPublico, estado);

            JOptionPane.showMessageDialog(rootPane, 
                "Habitacion añadida correctamente\n" +
                "Precio publico calculado: " + String.format("%.2f", precioPublico) + " €");
            dispose();

        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error guardando habitacion", e);
            JOptionPane.showMessageDialog(rootPane, 
                "Error al guardar: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }                                              

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                                
        dispose();
    }                                               

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jetNumHab = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jsCapacidad = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jsPrecioB = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jcbFormulas = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new java.awt.GridLayout(7, 2, 0, 20));

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelNombre.setText("Nueva habitacion");
        jPanel2.add(jLabelNombre);
        jPanel2.add(jLabel6);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Numero de habitacion");
        jPanel2.add(jLabel1);
        jPanel2.add(jetNumHab);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tipo");
        jPanel2.add(jLabel2);

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Duplex", "Junior", "Presidencial" }));
        jPanel2.add(jcbTipo);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Capacidad");
        jPanel2.add(jLabel3);
        jPanel2.add(jsCapacidad);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Precio base");
        jPanel2.add(jLabel4);
        jPanel2.add(jsPrecioB);
        jPanel2.add(jLabel7);

        jcbFormulas.setSelected(true);
        jcbFormulas.setText("¿Usar formulas de precio?");
        jPanel2.add(jcbFormulas);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Estado");
        jPanel2.add(jLabel5);

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Reparacion" }));
        jPanel2.add(jcbEstado);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAceptar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        FlatCobalt2IJTheme.setup();

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogAnadirHabitaciones dialog = new JDialogAnadirHabitaciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JCheckBox jcbFormulas;
    private javax.swing.JComboBox<String> jcbTipo;
    private javax.swing.JTextField jetNumHab;
    private javax.swing.JSpinner jsCapacidad;
    private javax.swing.JSpinner jsPrecioB;
    // End of variables declaration//GEN-END:variables
}