/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;


import Controlador.ClienteDAO;
import Controlador.ConexionBBDD;
import Modelo.Cliente;
import com.formdev.flatlaf.intellijthemes.FlatCobalt2IJTheme;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JTable;

/**
 *
 * @author DAM2Alu3
 */
public class JDialogCliente extends javax.swing.JDialog {
    private JTable JDialogClienteTable;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogCliente.class.getName());
    private ClienteDAO cl = new ClienteDAO();

    /**
     * Creates new form 
     */
    
    JFrameLogin jframepadre;
    private String dni;
    
    public JDialogCliente(java.awt.Frame parent, boolean modal, JTable tabla) {
        super(parent, modal);
        //jframepadre = (JFrameLogin)parent;
        initComponents();
        this.JDialogClienteTable = tabla;
        //jSpinnerFecha_nac.setValue("");
        setTitle("Cliente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelClientes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelDNI = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApelliod1 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jLabelApellido2 = new javax.swing.JLabel();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jLabelFecha_nac = new javax.swing.JLabel();
        jSpinnerFecha_nac = new javax.swing.JSpinner();
        jLabelMail = new javax.swing.JLabel();
        jTextFieldMail = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelNacionalidad = new javax.swing.JLabel();
        jTextFieldNacionalidad = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPais = new javax.swing.JLabel();
        jTextFieldPais = new javax.swing.JTextField();
        jLabelPoblacion = new javax.swing.JLabel();
        jTextFieldPoblacion = new javax.swing.JTextField();
        jLabelCalle_num = new javax.swing.JLabel();
        jTextFieldCalle_num = new javax.swing.JTextField();
        jLabelPiso = new javax.swing.JLabel();
        jTextFieldPiso = new javax.swing.JTextField();
        jButtonCrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelLogoP = new javax.swing.JLabel();
        jLabelJulia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelClientes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelClientes.setText("CLIENTES");

        jPanel1.setLayout(new java.awt.GridLayout(13, 2, 10, 10));

        jLabelDNI.setText("   DNI*");
        jPanel1.add(jLabelDNI);
        jPanel1.add(jTextFieldDNI);

        jLabelNombre.setText("   Nombre*");
        jPanel1.add(jLabelNombre);

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNombre);

        jLabelApelliod1.setText("   Apellido1*");
        jPanel1.add(jLabelApelliod1);
        jPanel1.add(jTextFieldApellido1);

        jLabelApellido2.setText("   Apellido2");
        jPanel1.add(jLabelApellido2);

        jTextFieldApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellido2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldApellido2);

        jLabelFecha_nac.setText("   Fecha de nacimiento*");
        jPanel1.add(jLabelFecha_nac);

        jSpinnerFecha_nac.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        jSpinnerFecha_nac.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFecha_nac, "dd/MM/yyyy"));
        jPanel1.add(jSpinnerFecha_nac);

        jLabelMail.setText("   Correo*");
        jPanel1.add(jLabelMail);

        jTextFieldMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMailActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldMail);

        jLabelTelefono.setText("   Teléfono*");
        jPanel1.add(jLabelTelefono);

        jTextFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTelefono);

        jLabelNacionalidad.setText("   Nacionalidad*");
        jPanel1.add(jLabelNacionalidad);
        jPanel1.add(jTextFieldNacionalidad);

        jLabelDireccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDireccion.setText("____________   Dirección de domicilio");
        jPanel1.add(jLabelDireccion);

        jLabel2.setText("____________________________");
        jPanel1.add(jLabel2);

        jLabelPais.setText("   País de residencia actual*");
        jPanel1.add(jLabelPais);

        jTextFieldPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPaisActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPais);

        jLabelPoblacion.setText("   Población*");
        jPanel1.add(jLabelPoblacion);
        jPanel1.add(jTextFieldPoblacion);

        jLabelCalle_num.setText("   Calle y número*");
        jPanel1.add(jLabelCalle_num);
        jPanel1.add(jTextFieldCalle_num);

        jLabelPiso.setText("   Piso");
        jPanel1.add(jLabelPiso);
        jPanel1.add(jTextFieldPiso);

        jButtonCrear.setText("Aceptar");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jLabelLogoP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoHoteliaMuyChiquito.png"))); // NOI18N

        jLabelJulia.setText("Julia Castarlenas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabelLogoP))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelJulia)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCrear)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLogoP)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelClientes)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCrear)
                .addGap(1, 1, 1)
                .addComponent(jLabelJulia)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMailActionPerformed

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        try {
            // TODO add your handling code here:
            Cliente nuevo = new Cliente(
                jTextFieldDNI.getText(),
                jTextFieldNombre.getText(),
                jTextFieldApellido1.getText(),
                jTextFieldApellido2.getText(),
                (Date) jSpinnerFecha_nac.getValue(),
                jTextFieldMail.getText(),
                jTextFieldTelefono.getText(),
                jTextFieldNacionalidad.getText(),
                jTextFieldPais.getText(),
                jTextFieldCalle_num.getText(),
                jTextFieldPoblacion.getText(),
                jTextFieldPiso.getText()
            );

                int resultado;

                // CREAR
                if (dni == null) {

                    resultado = cl.insertaCliente(nuevo);

                    if (resultado >= 1) {
                        jLabel1.setText("Creado con exito");
                    } else {
                        jLabel1.setText("No se ha creado");
                    }

                // EDITAR
                } else {

                    resultado = cl.editarCliente(nuevo, dni);

                    if (resultado >= 1) {
                        jLabel1.setText("Editado con exito");
                    } else {
                        jLabel1.setText("No se ha editado");
                    }
                }

                dispose();

            } catch (SQLException ex) {
                System.getLogger(JDialogCliente.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jTextFieldApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellido2ActionPerformed

    private void jTextFieldPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatCobalt2IJTheme.setup();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelApelliod1;
    private javax.swing.JLabel jLabelCalle_num;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelFecha_nac;
    private javax.swing.JLabel jLabelJulia;
    private javax.swing.JLabel jLabelLogoP;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelNacionalidad;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelPiso;
    private javax.swing.JLabel jLabelPoblacion;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerFecha_nac;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldCalle_num;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldNacionalidad;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPais;
    private javax.swing.JTextField jTextFieldPiso;
    private javax.swing.JTextField jTextFieldPoblacion;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables

   void setDniNie(String dni) throws SQLException {
        this.dni = dni;

        Cliente cliente = cl.buscaCliente(dni);

        jTextFieldDNI.setText(cliente.getDni_nie());
        jTextFieldNombre.setText(cliente.getNombre());
        jTextFieldApellido1.setText(cliente.getApellido1());
        jTextFieldApellido2.setText(cliente.getApellido2());
        jSpinnerFecha_nac.setValue(cliente.getFecha_nac());
        jTextFieldMail.setText(cliente.getMail());
        jTextFieldTelefono.setText(cliente.getTelefono());
        jTextFieldNacionalidad.setText(cliente.getNacionalidad());
        jTextFieldPais.setText(cliente.getPais());
        jTextFieldCalle_num.setText(cliente.getCalle_numero());
        jTextFieldPoblacion.setText(cliente.getPoblacion());
        jTextFieldPiso.setText(cliente.getPiso());

        jTextFieldDNI.setEditable(false);
    }
   }
