/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E07_RadioButtons;

import java.awt.Color;
import java.util.Enumeration;
import javax.swing.JRadioButton;

/**
 *
 * @author DAM2Alu3
 */
public class JFrameRadio_Mejorado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameRadio.class.getName());

    String colores[]={"Naranja", "Rosa", "Amarillo", "Verde", "Morado"};
    JRadioButton[] jrb = new JRadioButton[colores.length];
    /**
     * Creates new form JFrameRadio
     */
    public JFrameRadio_Mejorado() {
        initComponents();
        int pos = 0;
        for(String color : colores){
            jrb[pos]=new JRadioButton(color);
            buttonGroup1Colores.add(jrb[pos]);
            jPanel1Radio.add(jrb[pos]);
            pos++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1Colores = new javax.swing.ButtonGroup();
        jLabel1Resultado = new javax.swing.JLabel();
        jPanel1Radio = new javax.swing.JPanel();
        jButton1Seleccionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1Resultado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1Resultado.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1Resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Resultado.setText("SIN COLOR");

        jPanel1Radio.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1Radio.setLayout(new javax.swing.BoxLayout(jPanel1Radio, javax.swing.BoxLayout.PAGE_AXIS));

        jButton1Seleccionar.setText("Seleccionar");
        jButton1Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SeleccionarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("COLORES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1Resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1Radio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButton1Seleccionar)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jPanel1Radio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1Seleccionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(144, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SeleccionarActionPerformed
        // TODO add your handling code here:
       /* if(jRadioButton1Verde.isSelected()){
            jLabel1Resultado.setText(jRadioButton1Verde.getText());
            jLabel1Resultado.setForeground(Color.green);

        } else if (jRadioButton1Rojo.isSelected()) {
            jLabel1Resultado.setText(jRadioButton1Rojo.getText());
            jLabel1Resultado.setForeground(Color.red);
        } else if(jRadioButton1Azul.isSelected()){
            jLabel1Resultado.setText(jRadioButton1Azul.getText());
            jLabel1Resultado.setForeground(Color.blue);
        }*/
       
       Enumeration e = buttonGroup1Colores.getElements();
       while(e.hasMoreElements()){
           JRadioButton rb = (JRadioButton)e.nextElement();
           if(rb.isSelected())
               jLabel1Resultado.setText(rb.getText());
       }
    }//GEN-LAST:event_jButton1SeleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameRadio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1Colores;
    private javax.swing.JButton jButton1Seleccionar;
    private javax.swing.JLabel jLabel1Resultado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1Radio;
    // End of variables declaration//GEN-END:variables
}
