/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E12_OptionPane;

import javax.swing.JOptionPane;

/**
 *
 * @author DAM2Alu3
 */
public class JFrameEdad extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameEdad.class.getName());

    /**
     * Creates new form JFrameEdad
     */
    public JFrameEdad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonEdad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edad");
        jPanel1.add(jLabel1);

        jTextFieldEdad.setEditable(false);
        jTextFieldEdad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldEdad.setText("0");
        jPanel1.add(jTextFieldEdad);
        jPanel1.add(jLabel2);

        jButtonEdad.setText("Edad");
        jButtonEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEdadActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEdad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEdadActionPerformed
        // TODO add your handling code here:
        
        String edad = JOptionPane.showInputDialog(rootPane, 
                "Introduce la edad", 
                "Edad", 
                JOptionPane.QUESTION_MESSAGE);
        
        jTextFieldEdad.setText(edad);
        
        int resultado = JOptionPane.showConfirmDialog(rootPane, 
                "La edad introducida es: " + edad , 
                "Edad Introducida" , 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.INFORMATION_MESSAGE);
       
        if(resultado == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(rootPane, 
                    "Damos por buena la edad de " + edad , 
                    "Mensaje confirmacion",
                    JOptionPane.PLAIN_MESSAGE); 
                    
        }
    }//GEN-LAST:event_jButtonEdadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameEdad().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEdad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldEdad;
    // End of variables declaration//GEN-END:variables
}
