/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E16_Listeners;

/**
 *
 * @author DAM2Alu3
 */
public class JFrame2Teclas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame2Teclas.class.getName());

    /**
     * Creates new form JFrame2Teclas
     */
    public JFrame2Teclas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelLostFocus = new javax.swing.JLabel();
        jTextFieldLostFocus = new javax.swing.JTextField();
        jLabelKeyPressed = new javax.swing.JLabel();
        jTextFieldKeyPressed = new javax.swing.JTextField();
        jLabelKeyReleased = new javax.swing.JLabel();
        jTextFieldKeyReleased = new javax.swing.JTextField();
        jLabeKeyTyped = new javax.swing.JLabel();
        jTextFieldKeyTyped = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(5, 2, 10, 10));

        jLabelNombre.setText("Nombre");
        jPanel1.add(jLabelNombre);

        jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusLost(evt);
            }
        });
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldNombre);

        jLabelLostFocus.setText("Lost Focus");
        jPanel1.add(jLabelLostFocus);

        jTextFieldLostFocus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLostFocusActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldLostFocus);

        jLabelKeyPressed.setText("Key Pressed");
        jPanel1.add(jLabelKeyPressed);

        jTextFieldKeyPressed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKeyPressedActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldKeyPressed);

        jLabelKeyReleased.setText("Key Released");
        jPanel1.add(jLabelKeyReleased);

        jTextFieldKeyReleased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKeyReleasedActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldKeyReleased);

        jLabeKeyTyped.setText("Key Typed");
        jPanel1.add(jLabeKeyTyped);

        jTextFieldKeyTyped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKeyTypedActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldKeyTyped);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldLostFocusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLostFocusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLostFocusActionPerformed

    private void jTextFieldKeyPressedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKeyPressedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKeyPressedActionPerformed

    private void jTextFieldKeyReleasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKeyReleasedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKeyReleasedActionPerformed

    private void jTextFieldKeyTypedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKeyTypedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKeyTypedActionPerformed

    private void jTextFieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusLost
        // TODO add your handling code here:
        jTextFieldLostFocus.setText(jTextFieldNombre.getText());
    }//GEN-LAST:event_jTextFieldNombreFocusLost

    private void jTextFieldNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyPressed
        // TODO add your handling code here:
        jTextFieldKeyPressed.setText(jTextFieldNombre.getText());
    }//GEN-LAST:event_jTextFieldNombreKeyPressed

    private void jTextFieldNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyReleased
        // TODO add your handling code here:
        jTextFieldKeyReleased.setText(jTextFieldNombre.getText());

    }//GEN-LAST:event_jTextFieldNombreKeyReleased

    private void jTextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyTyped
        // TODO add your handling code here:
        jTextFieldKeyTyped.setText(jTextFieldNombre.getText());

    }//GEN-LAST:event_jTextFieldNombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrame2Teclas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabeKeyTyped;
    private javax.swing.JLabel jLabelKeyPressed;
    private javax.swing.JLabel jLabelKeyReleased;
    private javax.swing.JLabel jLabelLostFocus;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldKeyPressed;
    private javax.swing.JTextField jTextFieldKeyReleased;
    private javax.swing.JTextField jTextFieldKeyTyped;
    private javax.swing.JTextField jTextFieldLostFocus;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
