/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;


import Controlador.ConexionBBDD;
import Modelo.Cliente;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;

/**
 *
 * @author DAM2Alu3
 */
public class JDialogReserva extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogReserva.class.getName());

    /**
     * Creates new form JDialogAltaCliente
     */
    
    JFrameLogin jframepadre;
    
    public JDialogReserva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        //jframepadre = (JFrameLogin)parent;
        initComponents();
        //jSpinnerFecha_nac.setValue("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelClientes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelDNI = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jLabelFecha_nac = new javax.swing.JLabel();
        jSpinnerFecha_nac = new javax.swing.JSpinner();
        jLabelFecha_nac1 = new javax.swing.JLabel();
        jSpinnerFecha_nac1 = new javax.swing.JSpinner();
        jLabelApellido2 = new javax.swing.JLabel();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApelliod1 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jButtonCrear = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelClientes.setText("RESERVA");

        jPanel1.setLayout(new java.awt.GridLayout(7, 2, 10, 10));

        jLabelDNI.setText("DNI cliente");
        jPanel1.add(jLabelDNI);
        jPanel1.add(jTextFieldDNI);

        jLabelFecha_nac.setText("Fecha de inicio");
        jPanel1.add(jLabelFecha_nac);

        jSpinnerFecha_nac.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFecha_nac.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFecha_nac, "dd/MM/yyyy"));
        jPanel1.add(jSpinnerFecha_nac);

        jLabelFecha_nac1.setText("Fecha de fin");
        jPanel1.add(jLabelFecha_nac1);

        jSpinnerFecha_nac1.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFecha_nac1.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFecha_nac1, "dd/MM/yyyy"));
        jPanel1.add(jSpinnerFecha_nac1);

        jLabelApellido2.setText("Cantidad de personas");
        jPanel1.add(jLabelApellido2);

        jTextFieldApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellido2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldApellido2);

        jLabelNombre.setText("Fecha hora reserva");
        jPanel1.add(jLabelNombre);

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNombre);

        jLabelApelliod1.setText("Estado");
        jPanel1.add(jLabelApelliod1);

        jTextFieldApellido1.setEditable(false);
        jTextFieldApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellido1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldApellido1);

        jButtonCrear.setText("Crear");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEditar)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonCrear)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClientes)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrear)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButton1))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        try {
            // TODO add your handling code here:
            ConexionBBDD c = new ConexionBBDD();
            Connection conexion = c.getConnection();
            
            
            Cliente nuevo = new Cliente(
                    jTextFieldDNI.getText(),
                    jTextFieldNombre.getText(),
                    jTextFieldApellido1.getText(),
                    jTextFieldApellido2.getText(),
                    (Date)jSpinnerFecha_nac.getValue(),
                    jTextFieldMail.getText(),
                    jTextFieldTelefono.getText(),
                    jTextFieldNacionalidad.getText(),
                    jTextFieldPais.getText(),
                    jTextFieldCalle_num.getText(),
                    jTextFieldPoblacion.getText(),
                    jTextFieldPiso.getText()
            );
            
            if(c.insertaCliente(nuevo)>=1){
                jLabel1.setText("Creado con exito");
            }else{
                jLabel1.setText("No se ha creado");

            }
            //dispose();  cierra el jdialog
            
            
        } catch (SQLException ex) {
            System.getLogger(JDialogReserva.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jTextFieldApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellido2ActionPerformed

    @SuppressWarnings("empty-statement")
    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            // TODO add your handling code here:
            
            ConexionBBDD c = new ConexionBBDD();
            Connection conexion = c.getConnection();
            
            String dni = jTextFieldDNI.getText();
            Cliente cliente = c.buscaCliente(dni);
            
            if(cliente == null){
                jLabel1.setText("No se ha encontrado");

            }else{
                jLabel1.setText("Encontrado");
                
                jTextFieldDNI.setText(cliente.getDni_nie());
                jTextFieldNombre.setText(cliente.getNombre());
                jTextFieldApellido1.setText(cliente.getApellido1());
                jTextFieldApellido2.setText(cliente.getApellido2());
                jSpinnerFecha_nac.setValue(cliente.getFecha_nac());
                jTextFieldMail.setText(cliente.getMail());
                jTextFieldTelefono.setText(cliente.getTelefono());
                jTextFieldNacionalidad.setText(cliente.getNacionalidad());
                jTextFieldPais.setText(cliente.getPais());
                jTextFieldPoblacion.setText(cliente.getPoblacion());
                jTextFieldCalle_num.setText(cliente.getCalle_numero());
                jTextFieldPiso.setText(cliente.getPiso());
                
            }
        } catch (SQLException ex) {
            System.getLogger(JDialogReserva.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        try {
            // TODO add your handling code here:
            ConexionBBDD c = new ConexionBBDD();
            Connection conexion = c.getConnection();
            
            Cliente nuevo = new Cliente(
                    jTextFieldDNI.getText(),
                    jTextFieldNombre.getText(),
                    jTextFieldApellido1.getText(),
                    jTextFieldApellido2.getText(),
                    (Date)jSpinnerFecha_nac.getValue(),
                    jTextFieldMail.getText(),
                    jTextFieldTelefono.getText(),
                    jTextFieldNacionalidad.getText(),
                    jTextFieldPais.getText(),
                    jTextFieldCalle_num.getText(),
                    jTextFieldPoblacion.getText(),
                    jTextFieldPiso.getText()
            );
            
            if(c.editarCliente(nuevo, jTextFieldDNI.getText()) >= 1){
                jLabel1.setText("Actualizado con exito");
            }else{
                jLabel1.setText("No se ha actualizado");

            }
            
        } catch (SQLException ex) {
            System.getLogger(JDialogReserva.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            jLabel1.setText("Error");
        }
        
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellido1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogReserva dialog = new JDialogReserva(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelApelliod1;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelFecha_nac;
    private javax.swing.JLabel jLabelFecha_nac1;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerFecha_nac;
    private javax.swing.JSpinner jSpinnerFecha_nac1;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
