/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;


import Modelo.Cliente;
import java.util.Date;

/**
 *
 * @author DAM2Alu3
 */
public class JDialogCliente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogCliente.class.getName());

    /**
     * Creates new form JDialogAltaCliente
     */
    
    JFrameLogin jframepadre;
    
    public JDialogCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        jframepadre = (JFrameLogin)parent;
        initComponents();
        jSpinnerFecha_nac.setValue(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelClientes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelDNI = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApelliod1 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jLabelApellido2 = new javax.swing.JLabel();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jLabelFecha_nac = new javax.swing.JLabel();
        jSpinnerFecha_nac = new javax.swing.JSpinner();
        jLabelMail = new javax.swing.JLabel();
        jTextFieldMail = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelNacionalidad = new javax.swing.JLabel();
        jTextFieldNacionalidad = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPais = new javax.swing.JLabel();
        jTextFieldPais = new javax.swing.JTextField();
        jLabelPoblacion = new javax.swing.JLabel();
        jTextFieldPoblacion = new javax.swing.JTextField();
        jLabelCalle_num = new javax.swing.JLabel();
        jTextFieldCalle_num = new javax.swing.JTextField();
        jLabelPiso = new javax.swing.JLabel();
        jTextFieldPiso = new javax.swing.JTextField();
        jButtonAlta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelClientes.setText("CLIENTES");

        jPanel1.setLayout(new java.awt.GridLayout(13, 2, 10, 10));

        jLabelDNI.setText("DNI");
        jPanel1.add(jLabelDNI);
        jPanel1.add(jTextFieldDNI);

        jLabelNombre.setText("Nombre");
        jPanel1.add(jLabelNombre);

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNombre);

        jLabelApelliod1.setText("Apellido1");
        jPanel1.add(jLabelApelliod1);
        jPanel1.add(jTextFieldApellido1);

        jLabelApellido2.setText("Apellido2");
        jPanel1.add(jLabelApellido2);

        jTextFieldApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellido2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldApellido2);

        jLabelFecha_nac.setText("Fecha de nacimiento");
        jPanel1.add(jLabelFecha_nac);

        jSpinnerFecha_nac.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFecha_nac.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFecha_nac, "dd/MM/yyyy"));
        jPanel1.add(jSpinnerFecha_nac);

        jLabelMail.setText("Correo");
        jPanel1.add(jLabelMail);

        jTextFieldMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMailActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldMail);

        jLabelTelefono.setText("Teléfono");
        jPanel1.add(jLabelTelefono);

        jTextFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTelefono);

        jLabelNacionalidad.setText("Nacionalidad");
        jPanel1.add(jLabelNacionalidad);
        jPanel1.add(jTextFieldNacionalidad);

        jLabelDireccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDireccion.setText("____________   Dirección de domicilio");
        jPanel1.add(jLabelDireccion);

        jLabel2.setText("______________________________________");
        jPanel1.add(jLabel2);

        jLabelPais.setText("País de residencia actual");
        jPanel1.add(jLabelPais);

        jTextFieldPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPaisActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPais);

        jLabelPoblacion.setText("Población");
        jPanel1.add(jLabelPoblacion);
        jPanel1.add(jTextFieldPoblacion);

        jLabelCalle_num.setText("Calle y número");
        jPanel1.add(jLabelCalle_num);
        jPanel1.add(jTextFieldCalle_num);

        jLabelPiso.setText("Piso");
        jPanel1.add(jLabelPiso);
        jPanel1.add(jTextFieldPiso);

        jButtonAlta.setText("Alta");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonAlta)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAlta)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMailActionPerformed

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        // TODO add your handling code here:
        Cliente nuevo = new Cliente(
                        jTextFieldDNI.getText(),
                        jTextFieldNombre.getText(),
                        jTextFieldApellido1.getText(),
                        jTextFieldApellido2.getText(),
                        (Date)jSpinnerFecha_nac.getValue(),
                        jTextFieldMail.getText(),
                        jTextFieldTelefono.getText(),
                        jTextFieldNacionalidad.getText(),
                        jTextFieldPais.getText(),
                        jTextFieldCalle_num.getText(),
                        jTextFieldPoblacion.getText(),
                        jTextFieldPiso.getText()
                        );
        
        jframepadre.addCliente(nuevo);
        dispose();
    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void jTextFieldApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellido2ActionPerformed

    private void jTextFieldPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogCliente dialog = new JDialogCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelApelliod1;
    private javax.swing.JLabel jLabelCalle_num;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelFecha_nac;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelNacionalidad;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelPiso;
    private javax.swing.JLabel jLabelPoblacion;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerFecha_nac;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldCalle_num;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldNacionalidad;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPais;
    private javax.swing.JTextField jTextFieldPiso;
    private javax.swing.JTextField jTextFieldPoblacion;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
