/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.ConexionBBDD;
import Modelo.Habitacion;

/**
 *
 * @author DAM2Alu16
 */
public class JDialogEditarHabitaciones extends javax.swing.JDialog {
    /**
     * No terminado
     * 
     * En esta clase crear una interfaz que te permita ver y editar las habitaciones por su id(recogido en el calendario)
     * tiene arriba : Habitacion "idHabitacion"
     * saldran los campos numero, tipo, capacidad, precio_base, estado
     * 
     * para el precio_base un check para usar solo el precio base y no la formula a partir del precio_base
     * 
     * para el estado, solo se podra poner de reparacion a libre, si esta ocupado no se podra
     */
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogEditarHabitaciones.class.getName());
    //VARIABLES
    ConexionBBDD database = new ConexionBBDD();
    
    //esta variable cambiarla y traerla por calendario
    int idHabitacion = 1;
    
    public void MostrarEditable(int idHabitacion) {
        Habitacion habitacion = database.buscarHabitacionPorId(idHabitacion);
        jLabelNombre.setText("Habitaicion "+idHabitacion);
        jetNumHab.setText(String.valueOf(habitacion.getNumero()));
        jcbTipo.setSelectedItem(habitacion.getTipo());
        jsCapacidad.setValue(habitacion.getCapacidad());
        jsPrecioB.setValue(habitacion.getPrecio_base());
        jcbEstado.setSelectedItem(habitacion.getEstado());
         
    }
    
    
    
    /**
     * Creates new form JDialogEditarHabitaciones
     */
    public JDialogEditarHabitaciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        MostrarEditable(idHabitacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jetNumHab = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jsCapacidad = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jsPrecioB = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jcbFormulas = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new java.awt.GridLayout(7, 2, 0, 20));

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelNombre.setText("Habitacion id");
        jPanel2.add(jLabelNombre);
        jPanel2.add(jLabel6);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Número de habitación");
        jPanel2.add(jLabel1);
        jPanel2.add(jetNumHab);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tipo de habitación");
        jPanel2.add(jLabel2);

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Duplex", "Junior", "Presidencial" }));
        jPanel2.add(jcbTipo);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Capacidad de la habitación");
        jPanel2.add(jLabel3);
        jPanel2.add(jsCapacidad);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Precio base");
        jPanel2.add(jLabel4);
        jPanel2.add(jsPrecioB);
        jPanel2.add(jLabel7);

        jcbFormulas.setSelected(true);
        jcbFormulas.setText("¿Usar formulas de precio?");
        jPanel2.add(jcbFormulas);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Estado de la habitación");
        jPanel2.add(jLabel5);

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Reparacion" }));
        jPanel2.add(jcbEstado);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonCancelar.setText("Cancelar");
        jPanel1.add(jButtonCancelar);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAceptar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        //boton que actualiza los datos puestos en la habitacion
        //hay que hacer ifs para que no sea null
        
        //int idHabitacion
        int numero 
        String tipo
        int capacidad
        double precio_base
        String estado 
        
        
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogEditarHabitaciones dialog = new JDialogEditarHabitaciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JCheckBox jcbFormulas;
    private javax.swing.JComboBox<String> jcbTipo;
    private javax.swing.JTextField jetNumHab;
    private javax.swing.JSpinner jsCapacidad;
    private javax.swing.JSpinner jsPrecioB;
    // End of variables declaration//GEN-END:variables
}
