/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.ConexionBBDD;
import Controlador.Seguridad;
import Modelo.Empleado;
import java.util.Date;

/**
 *
 * @author DAM2Alu4
 */
public class JDialogCrearEmpleado extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogCrearEmpleado.class.getName());

    ConexionBBDD c = new ConexionBBDD();

    public JDialogCrearEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Crear empleados");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelid = new javax.swing.JLabel();
        jTextDNI_NIE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jLabelApellido2 = new javax.swing.JLabel();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jLabelFechaAlta = new javax.swing.JLabel();
        jSpinnerFechaAlt = new javax.swing.JSpinner();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelContraseña1 = new javax.swing.JLabel();
        jTContraseña1 = new javax.swing.JTextField();
        jLabelContraseña2 = new javax.swing.JLabel();
        jTContraseña2 = new javax.swing.JTextField();
        jLabelRol = new javax.swing.JLabel();
        jComboBoxROL = new javax.swing.JComboBox<>();
        jLabelCorreo = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelNacionalidad = new javax.swing.JLabel();
        jTextFieldNacionalidad = new javax.swing.JTextField();
        jLabelPais = new javax.swing.JLabel();
        jTextFieldPoblacion = new javax.swing.JTextField();
        jLabelCalle_numero = new javax.swing.JLabel();
        jTextFieldCalle_Numero = new javax.swing.JTextField();
        jLabelPoblacion = new javax.swing.JLabel();
        jTextFieldPais = new javax.swing.JTextField();
        jLabelPiso = new javax.swing.JLabel();
        jTextFieldPiso = new javax.swing.JTextField();
        jButtonAlta = new javax.swing.JButton();
        jLabelPosibleError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACTUALIZAR EMPLEADOS");

        jPanel1.setLayout(new java.awt.GridLayout(16, 2, 10, 10));

        jLabelid.setText("DNI");
        jPanel1.add(jLabelid);
        jPanel1.add(jTextDNI_NIE);

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jPanel1.add(jTextFieldNombre);

        jLabel3.setText("Apellido1 ");
        jPanel1.add(jLabel3);
        jPanel1.add(jTextFieldApellido1);

        jLabelApellido2.setText("Apellido2");
        jPanel1.add(jLabelApellido2);
        jPanel1.add(jTextFieldApellido2);

        jLabelFechaAlta.setText("Fecha Nacimiento");
        jPanel1.add(jLabelFechaAlta);

        jSpinnerFechaAlt.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFechaAlt.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFechaAlt, "dd/MM/yy"));
        jPanel1.add(jSpinnerFechaAlt);

        jLabelUsuario.setText("Usuario");
        jPanel1.add(jLabelUsuario);
        jPanel1.add(jTextFieldUsuario);

        jLabelContraseña1.setText("Contraseña");
        jPanel1.add(jLabelContraseña1);
        jPanel1.add(jTContraseña1);

        jLabelContraseña2.setText("Contraseña");
        jPanel1.add(jLabelContraseña2);
        jPanel1.add(jTContraseña2);

        jLabelRol.setText("Rol");
        jPanel1.add(jLabelRol);

        jComboBoxROL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "recepcionista", "servicio" }));
        jComboBoxROL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxROLItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxROL);

        jLabelCorreo.setText("Correo");
        jPanel1.add(jLabelCorreo);
        jPanel1.add(jTextFieldCorreo);

        jLabelTelefono.setText("Telefono");
        jPanel1.add(jLabelTelefono);
        jPanel1.add(jTextFieldTelefono);

        jLabelNacionalidad.setText("Nacionalidad");
        jPanel1.add(jLabelNacionalidad);
        jPanel1.add(jTextFieldNacionalidad);

        jLabelPais.setText("País");
        jPanel1.add(jLabelPais);
        jPanel1.add(jTextFieldPoblacion);

        jLabelCalle_numero.setText("Calle_numero");
        jPanel1.add(jLabelCalle_numero);
        jPanel1.add(jTextFieldCalle_Numero);

        jLabelPoblacion.setText("Población");
        jPanel1.add(jLabelPoblacion);
        jPanel1.add(jTextFieldPais);

        jLabelPiso.setText("Piso");
        jPanel1.add(jLabelPiso);
        jPanel1.add(jTextFieldPiso);

        jButtonAlta.setText("Crear");
        jButtonAlta.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jLabelPosibleError.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelPosibleError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPosibleError, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAlta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPosibleError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Boton para Crear un Empleado
     *
     * @param evt
     */
    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed

        // parsear para que no de error el Date
        Date fecha = (Date) jSpinnerFechaAlt.getValue();
        // casteo a String el item de la combo box, asi me aseguro que no pongan mal el rol
        String rol = (String) jComboBoxROL.getSelectedItem();
        // haseo la contraseña del usuario y se la paso al empleado
        String contraseniaHas = Seguridad.hashPassword(jTContraseña1.getText());
        // consulto si el dni existe , si es true
        if (jTextDNI_NIE.getText().isEmpty() || c.consultaIdEmpleado(jTextDNI_NIE.getText())) {
            jLabelPosibleError.setText("El DNI_NIE ya existe o esta vacío ");
            return; // si no ponia return me daba error todo elrato por que entraba
        } else if (jTextFieldNombre.getText().isEmpty() || jTextFieldApellido1.getText().isEmpty() || fecha == null || jTextFieldUsuario.getText().isEmpty()
                || jTContraseña1.getText().isEmpty() || jTContraseña2.getText().isEmpty() || rol.isEmpty() || jTextFieldCorreo.getText().isEmpty()
                || jTextFieldTelefono.getText().isEmpty() || jTextFieldNacionalidad.getText().isEmpty() || jTextFieldPais.getText().isEmpty()
                || jTextFieldCalle_Numero.getText().isEmpty() || jTextFieldPoblacion.getText().isEmpty()) 
        {
            jLabelPosibleError.setText("Rellena todos los datos necesarios");
            return;
        } else if (!jTContraseña1.getText().equals(jTContraseña2.getText())) {
            jLabelPosibleError.setText("La contraseña es distinta, compueba");
            return;
        }
        // Creo el empleado en vacio
        Empleado empleado = new Empleado(
                jTextDNI_NIE.getText(),
                jTextFieldNombre.getText(),
                jTextFieldApellido1.getText(),
                jTextFieldApellido2.getText(),
                fecha,
                jTextFieldUsuario.getText(),
                contraseniaHas,
                rol,
                jTextFieldCorreo.getText(),
                jTextFieldTelefono.getText(),
                jTextFieldNacionalidad.getText(),
                jTextFieldPais.getText(),
                jTextFieldCalle_Numero.getText(),
                jTextFieldPoblacion.getText(),
                jTextFieldPiso.getText());
        boolean prueba = c.insertEmpleado(empleado);
        if (prueba == false) {
            jLabelPosibleError.setText("Error al crear el empleado");
        } else {
            jLabelPosibleError.setText("Empleado creado");
        }


    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void jComboBoxROLItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxROLItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxROLItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogCrearEmpleado dialog = new JDialogCrearEmpleado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JComboBox<String> jComboBoxROL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelCalle_numero;
    private javax.swing.JLabel jLabelContraseña1;
    private javax.swing.JLabel jLabelContraseña2;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelFechaAlta;
    private javax.swing.JLabel jLabelNacionalidad;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelPiso;
    private javax.swing.JLabel jLabelPoblacion;
    private javax.swing.JLabel jLabelPosibleError;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelid;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerFechaAlt;
    private javax.swing.JTextField jTContraseña1;
    private javax.swing.JTextField jTContraseña2;
    private javax.swing.JTextField jTextDNI_NIE;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldCalle_Numero;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNacionalidad;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPais;
    private javax.swing.JTextField jTextFieldPiso;
    private javax.swing.JTextField jTextFieldPoblacion;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
