/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;


import Controlador.ConexionBBDD;
import Modelo.Cliente;
import Modelo.Reserva;
import Modelo.Servicio;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import java.sql.ResultSet;


/**
 *
 * @author DAM2Alu3
 */
public class JDialogReserva extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogReserva.class.getName());

    /**
     * Creates new form JDialogAltaCliente
     */
    
    JFrameLogin jframepadre;
    
    private void cargarServicios() throws SQLException {
        ResultSet rs = null;
        ResultSet rs2 = null;
        try {
            ConexionBBDD c = new ConexionBBDD();
            Connection conexion = c.getConnection();
            rs = c.todosServicios();
            rs2 = c.todasHabitacionesLibres();
            jComboBoxReserva.removeAllItems(); // limpiamos combo
            
            while (rs.next()) {
                String nombre = rs.getString("nombre");
                
                jComboBoxReserva.addItem(nombre);
            }
            while (rs2.next()){
                String hab = rs2.getString("tipo");
                jComboBoxReserva.addItem(hab);
            }
            
        } catch (SQLException ex) {
            System.getLogger(JDialogReserva.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } finally {
            rs.close();
        }

}
    
    public JDialogReserva(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        //jframepadre = (JFrameLogin)parent;
        initComponents();
        //jSpinnerFecha_nac.setValue("");
        cargarServicios();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelClientes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelDNI = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxReserva = new javax.swing.JComboBox<>();
        jLabelFecha_nac = new javax.swing.JLabel();
        jSpinnerFecha_inicio = new javax.swing.JSpinner();
        jLabelFecha_nac1 = new javax.swing.JLabel();
        jSpinnerFecha_fin = new javax.swing.JSpinner();
        jLabelApellido2 = new javax.swing.JLabel();
        jSpinnerNPersonas = new javax.swing.JSpinner();
        jLabelNombre = new javax.swing.JLabel();
        jSpinnerFecha_reserva = new javax.swing.JSpinner();
        jLabelApelliod1 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jButtonCrear = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelClientes.setText("RESERVA");

        jPanel1.setLayout(new java.awt.GridLayout(7, 2, 10, 10));

        jLabelDNI.setText("DNI cliente");
        jPanel1.add(jLabelDNI);
        jPanel1.add(jTextFieldDNI);

        jLabel2.setText("Reserva");
        jPanel1.add(jLabel2);

        jComboBoxReserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxReserva);

        jLabelFecha_nac.setText("Fecha de inicio");
        jPanel1.add(jLabelFecha_nac);

        jSpinnerFecha_inicio.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFecha_inicio.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFecha_inicio, "dd/MM/yyyy"));
        jPanel1.add(jSpinnerFecha_inicio);

        jLabelFecha_nac1.setText("Fecha de fin");
        jPanel1.add(jLabelFecha_nac1);

        jSpinnerFecha_fin.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFecha_fin.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFecha_fin, "dd/MM/yyyy"));
        jPanel1.add(jSpinnerFecha_fin);

        jLabelApellido2.setText("Cantidad de personas");
        jPanel1.add(jLabelApellido2);
        jPanel1.add(jSpinnerNPersonas);

        jLabelNombre.setText("Fecha hora reserva");
        jPanel1.add(jLabelNombre);

        jSpinnerFecha_reserva.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFecha_reserva.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFecha_reserva, "dd/MM/yyyy HH:mm:ss"));
        jSpinnerFecha_reserva.setEnabled(false);
        jPanel1.add(jSpinnerFecha_reserva);

        jLabelApelliod1.setText("Estado");
        jPanel1.add(jLabelApelliod1);

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aceptada", "Cancelada" }));
        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxEstado);

        jButtonCrear.setText("Crear");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jButtonEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCrear))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrear)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonEliminar))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        try {
            // TODO add your handling code here:
            ConexionBBDD c = new ConexionBBDD();
            Connection conexion = c.getConnection();
            
            Reserva nuevo = new Reserva(
                    c.buscarServicioId(jComboBoxReserva.getSelectedItem().toString()),
                    c.buscarHabitacion(jComboBoxReserva.getSelectedItem().toString()),
                    c.buscaFactura(jTextFieldDNI.getText()).getIdFactura(), 
                    (int) jSpinnerNPersonas.getValue(),
                    jTextFieldDNI.getText(),
                    jComboBoxEstado.getSelectedItem().toString(),
                    (Date)jSpinnerFecha_inicio.getValue(),
                    (Date)jSpinnerFecha_fin.getValue(),
                    (Date)jSpinnerFecha_reserva.getValue()                        
            );
            
            if(c.insertaReserva(nuevo)>=1){
                jLabel1.setText("Creado con exito");
            }else{
                jLabel1.setText("No se ha creado");

            }
            //dispose();  cierra el jdialog
            
            
        } catch (SQLException ex) {
            System.getLogger(JDialogReserva.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jButtonCrearActionPerformed

    @SuppressWarnings("empty-statement")
    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            // TODO add your handling code here:
            
            ConexionBBDD c = new ConexionBBDD();
            Connection conexion = c.getConnection();
            
            String dni = jTextFieldDNI.getText();
            Reserva reserva = c.buscaReserva(dni);
            
            if(reserva == null){
                jLabel1.setText("No se ha encontrado");

            }else{
                jLabel1.setText("Encontrado");
                
                jTextFieldDNI.setText(reserva.getIdCliente());
                jComboBoxReserva.setSelectedItem());
                jSpinnerFecha_inicio.setValue(reserva.getFecha_inicio());
                jSpinnerFecha_fin.setValue(reserva.getFecha_fin());
                jSpinnerNPersonas.setValue(reserva.getIdCliente());
                jSpinnerFecha_reserva.setValue(reserva.getFecha_hora_reserva());
                jComboBoxEstado.setSelectedItem(reserva.getEstado());
            }
        } catch (SQLException ex) {
            System.getLogger(JDialogReserva.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        try {
            // TODO add your handling code here:
            ConexionBBDD c = new ConexionBBDD();
            Connection conexion = c.getConnection();
            
            Reserva nuevo = new Reserva(
                    c.buscarServicioId(jComboBoxReserva.getSelectedItem().toString()),
                    c.buscarHabitacion(jComboBoxReserva.getSelectedItem().toString()),
                    c.buscaFactura(jTextFieldDNI.getText()).getIdFactura(), 
                    (int) jSpinnerNPersonas.getValue(),
                    jTextFieldDNI.getText(),
                    jComboBoxEstado.getSelectedItem().toString(),
                    (Date)jSpinnerFecha_inicio.getValue(),
                    (Date)jSpinnerFecha_fin.getValue(),
                    (Date)jSpinnerFecha_reserva.getValue()                        
            );
            
            if(c.editarReserva(nuevo, jTextFieldDNI.getText(), ) >= 1){
                jLabel1.setText("Actualizado con exito");
            }else{
                jLabel1.setText("No se ha actualizado");

            }
            
        } catch (SQLException ex) {
            System.getLogger(JDialogReserva.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            jLabel1.setText("Error");
        }
        
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    JDialogReserva dialog = new JDialogReserva(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (SQLException ex) {
                    System.getLogger(JDialogReserva.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelApelliod1;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelFecha_nac;
    private javax.swing.JLabel jLabelFecha_nac1;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerFecha_fin;
    private javax.swing.JSpinner jSpinnerFecha_inicio;
    private javax.swing.JSpinner jSpinnerFecha_reserva;
    private javax.swing.JSpinner jSpinnerNPersonas;
    private javax.swing.JTextField jTextFieldDNI;
    // End of variables declaration//GEN-END:variables
}
