/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.ConexionBBDD;
import java.awt.Color;
import java.awt.Component;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DAM2Alu16
 * 
 * En este JDialog, se crea un JTable, el cual te muestra las habitaciones que tienes a la izquierda y a la derecha la fecha,
 * marcando cuando esta disponible, ocupada o en reparacion
 */
public class JDialogCalendarioHab extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogCalendarioHab.class.getName());

    
    ConexionBBDD database = new ConexionBBDD();
    DefaultTableModel dtm;
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    LocalDate dateActual;
    
   public void cargarCalendario() {
    // modelo sin filas prefijadas
    dtm = new DefaultTableModel();
    jTableCalenHab.setModel(dtm);

    // columna de habitaciones
    dtm.addColumn("Habitaciones");

    dateActual = LocalDate.now();

    // añade columnas de fechas de hoy a dos años 365 + 365 = 730 (igual se ve un poco incomodo, igual se cambia 😙)
    for (int i = 0; i < 730; i++) {
        LocalDate date = dateActual.plusDays(i);
        dtm.addColumn(date.format(dtf));
    }

    // aplica lo colores a traves de la clase de abajo
    jTableCalenHab.setDefaultRenderer(Object.class, new EstadoCellRenderer());
    jTableCalenHab.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

    List<String> habitaciones = database.buscarIdHabitaciones();

    for (int rowIndex = 0; rowIndex < habitaciones.size(); rowIndex++) {
        String idHabStr = habitaciones.get(rowIndex);
        int idHab = Integer.parseInt(idHabStr);

        Object[] fila = new Object[dtm.getColumnCount()];
        fila[0] = idHabStr;
        dtm.addRow(fila);

        List<Object[]> reservas = database.buscarFechayEstadoPorHabitacion(idHab);

        for (Object[] reg : reservas) {
            // reg[0] =  fecha inicio, reg[1] = fecga fin, reg[2] = estado
            LocalDate inicio = (LocalDate) reg[0];
            LocalDate fin = (LocalDate) reg[1];
            String estado = (String) reg[2];

            // si la reserva esta cancelada, no lo cuenta
            if (estado != null && estado.equalsIgnoreCase("Cancelado")) {
                continue;
            }

            // calcula indices relativos desde dateActual
            long ChronoInicio = ChronoUnit.DAYS.between(dateActual, inicio);
            long ChronoFinal = ChronoUnit.DAYS.between(dateActual, fin);

            // si no hay fecha entre esos campos lo ignoramos para que este un poquito mas optimizado 
            int inicioCol = (int) Math.max(0, ChronoInicio) + 1;
            int finCol = (int) Math.min(729, ChronoFinal) + 1;

            if (finCol < 1 || inicioCol > 730) continue;

            // una etiqueta pa los colores
            String etiqueta = "Ocupado";
            if (estado.equalsIgnoreCase("Reparacion") || estado.equalsIgnoreCase("En reparacion")) {
                etiqueta = "Reparacion";
            }

            for (int col = inicioCol; col <= finCol; col++) {
                dtm.setValueAt(etiqueta, rowIndex, col);
            }
        }

        // si esta en reparacion, toda la fila estara pintada de gris
        String estadoHab = database.buscarEstadoHabitacion(idHab);
        if (estadoHab != null && estadoHab.toLowerCase().contains("repar")) {
            for (int col = 1; col < dtm.getColumnCount(); col++) {
                dtm.setValueAt("Reparacion", rowIndex, col);
            }
        }
    }
}

    
    /**
     * Creates new form JDialogCalendarioHab
     */
    public JDialogCalendarioHab(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Calendario de habitaciones");
        cargarCalendario();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCalenHab = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnAnadir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableCalenHab.setBorder(new javax.swing.border.MatteBorder(null));
        jTableCalenHab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCalenHab.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTableCalenHab);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setBackground(new java.awt.Color(153, 255, 153));
        jLabel4.setText("Libre     ");
        jLabel4.setOpaque(true);
        jPanel3.add(jLabel4);

        jLabel3.setBackground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Ocupado   ");
        jLabel3.setOpaque(true);
        jPanel3.add(jLabel3);

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("En reparación  ");
        jLabel2.setOpaque(true);
        jPanel3.add(jLabel2);

        jLabel5.setText("                                                                        ");
        jPanel3.add(jLabel5);

        jLabel6.setText("Buscar:  ");
        jPanel3.add(jLabel6);

        jtfBuscar.setPreferredSize(new java.awt.Dimension(80, 22));
        jtfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscarKeyReleased(evt);
            }
        });
        jPanel3.add(jtfBuscar);

        jLabel1.setText("                                                                    ");
        jPanel3.add(jLabel1);

        BtnAnadir.setText("Añadir");
        BtnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnadirActionPerformed(evt);
            }
        });
        jPanel3.add(BtnAnadir);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonEditar);

        jButtonVolver.setText("Volver");
        jPanel3.add(jButtonVolver);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1062, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

    int row = jTableCalenHab.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una habitación primero.",
                                          "No hay seleccion",
                                          JOptionPane.ERROR_MESSAGE);
        return;
    }

    Object valor = jTableCalenHab.getValueAt(row, 0);

    int idHabitacion = Integer.parseInt(valor.toString());

    // Abrir JDialog de edición enviando el ID
    JDialogEditarHabitaciones editar = new JDialogEditarHabitaciones(
            (java.awt.Frame) this.getParent(),
            true,
            idHabitacion
    );
    editar.setVisible(true);
    cargarCalendario();

    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void BtnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnadirActionPerformed
        //te manda a anadirHabitaciones al pulsar el boton
        JDialogAnadirHabitaciones crear = new JDialogAnadirHabitaciones(
            (java.awt.Frame) this.getParent(),
            true
    );
    crear.setVisible(true);
    cargarCalendario();
    }//GEN-LAST:event_BtnAnadirActionPerformed

    private void jtfBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarKeyReleased
        // selecciona por el numero de id que busques
        String texto = jtfBuscar.getText().trim();

    // si está vacío → deselecciona todo 🤧
    if (texto.isEmpty()) {
        jTableCalenHab.clearSelection();
        return;
    }
    for (int row = 0; row < jTableCalenHab.getRowCount(); row++) {
        Object valor = jTableCalenHab.getValueAt(row, 0);

        if (valor != null && valor.toString().contains(texto)) {

            jTableCalenHab.setRowSelectionInterval(row, row);
            jTableCalenHab.scrollRectToVisible(
                jTableCalenHab.getCellRect(row, 0, true)
            );
            return; 
        }
    }
    jTableCalenHab.clearSelection();
    }//GEN-LAST:event_jtfBuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogCalendarioHab dialog = new JDialogCalendarioHab(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnadir;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCalenHab;
    private javax.swing.JTextField jtfBuscar;
    // End of variables declaration//GEN-END:variables
}

// ------------------ Renderer para colorear según estado ------------------
class EstadoCellRenderer extends DefaultTableCellRenderer {
    //una clase que renderiza colores en la tabla
    @Override
    public Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {

        Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

        // columna 0, son los ids, que salgan en blanco
        if (column == 0) {
            c.setBackground(Color.WHITE);
            c.setForeground(Color.BLACK);
            setText(value == null ? "" : value.toString());
            return c;
        }

        // si hay fechas que tengan su respetivo color
        String estado;
        if (value == null) {
            estado = "";
        } else {
            estado = value.toString().toLowerCase();
        }

        if (estado.contains("ocup")) {
            c.setBackground(new Color(0xFF6666)); // rojo
        } else if (estado.contains("repar")) {
            c.setBackground(new Color(0x666666)); // gris
            c.setForeground(Color.WHITE);
        } else {
            c.setBackground(new Color(0xCCFFCC)); // verde
            c.setForeground(Color.BLACK);
        }

        setText("");

        if (isSelected) {
            c.setBackground(table.getSelectionBackground());
            c.setForeground(table.getSelectionForeground());
        }

        return c;
    }
}
